hpi-schul-cloud/nuxt-client

.mergify.yml
These changes prevent inadvertent merging, since the mergebot can only be activated via the label after an approve has been issued and no changes are requested anymore.
Documentation: https://doc.mergify.io/conditions.html#attribute-list
=> #39 Allow merge flag only after approval

src/themes/default/styles/utility/_typography.scss
- The pull before had an recursion defintion issue of the base font size. the text base size was defined as `1rem * x` and 1rem (font-size at the html element) was defines as text base size.
Should be fixed now.
=> quickfix scaling

docs/storybook/ColorPicker.md, package-lock.json, package.json, src/components/atoms/ColorPicker.stories.js, src/components/atoms/ColorPicker.unit.js, src/components/atoms/ColorPicker.vue, stories/misc.stories.js
https://ticketsystem.schul-cloud.org/browse/VUE-56
- added external vue-swatches component
- needs to be extended for accesiblity
- aria label by is already an open issue and in work
- maybe we want to contribute https://saintplay.github.io/vue-swatches/
- component is relatively powerful, enables custom styling, different modes of display, e. g. https://saintplay.github.io/vue-swatches/#sub-inline-custom-u-i
=> added vue-swatches package, including story in storybook

src/components/legacy/TheTopBar.vue
- menu button is now visible and you can close the menu
=> cherrypick menubutton hotfix from #301

.travis.yml
currently reports are only uploaded after success (because if there is an error the integration test fails before the upload script)
- moved tthe upload script to travis where we have more control over it
=> Always Upload integration-test report

src/pages/news/_id/index.vue
- if the ID is not valid, the page will not get rendered and handled as a 404 => redirect to legacy client
=> validate params.id to be a valid mongoId

deploy/compose-client_brb.dummy, deploy/compose-client_default.dummy, deploy/compose-client_n21.dummy, deploy/compose-client_open.dummy
- users where logged out in staging because the API was not reachable. (was referring to test instead of staging and the authentication cookie was now availble for this subdomain)
- added the environment as a variable to all the compose files
=> hotfix/staging-deploy - add $SYSTEM to api url

.eslintrc.js, src/components/base/BaseLink.unit.js, src/components/base/BaseSelect.unit.js, src/components/base/BaseSpinner.unit.js, src/components/base/BaseTable/BaseTable.unit.js, src/components/legacy/TheTopBar.unit.js, src/components/molecules/TextEditor.unit.js, src/components/organisms/DropdownMenu.unit.js, src/components/organisms/FormNews.unit.js, src/components/organisms/Pagination.unit.js
- depends on #440
- enables `jest/prefer strict equal` rule. 
- All changes where done by the fix option of eslint
**Why?**
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/prefer-strict-equal.md
=> enable jest/prefer strict equal rule

.eslintrc.js, src/components/base/BaseInput/BaseInputCheckbox.unit.js, src/components/base/BaseInput/BaseInputHidden.unit.js, src/components/base/BaseInput/BaseInputRadio.unit.js, src/components/base/BaseSelect.unit.js, src/components/base/BaseTextarea.unit.js, src/components/base/BaseVideo.unit.js, src/components/molecules/TextEditor.unit.js
- depends on #441
- enables `jest/no-truthy-falsy` rule. 
**Why?**
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-truthy-falsy.md
=> enable jest/no-truthy-falsy rule

src/components/base/BaseInput/BaseInputCheckbox.vue
the issue was caused because of our visually-hidden class. This class moved the actual checkbox input to the very top left of the browser window. Whenever you now toggled the input by clicking on the table you focused it and the browser tried to scroll the checkbox into your viewport. The fix is pretty simple, just add a position:relative to the wrapping visable label so the visually-hidden class only moved the input to the very top left of the label itself.
Open the Storybook DataTable with 50 items per page. Toggle any checkbox at the bottom of the table. Your scroll position should not change anymore.
=> fix scroll on checkbox toggle

src/components/base/BaseButton.scss, src/components/molecules/ContextMenu.vue
The Issue only exists at /content, not in Storybook because of different order of CSS imports. We should investigate this further later on. For now, this should fix the issue.
The Problem existed because of the undefined order of CSS imports. To overwrite styles we need to be more specific therefore I:
- reduced the specificity of BaseButton CSS to make it easier to overwrite styles
https://cdn-media-1.freecodecamp.org/images/1*wH2JSH_fw4oiAH2eqTg4qA.png
**http://localhost:4000/content/**
=> bugfix Context Menu in LernStore

src/components/molecules/FabIcon.vue
- der FAB hat fälschlicherweise immer versucht ein event zu werden, was natürlich fehlschlägt, wenn statt einem event ein link übergeben wird.
=> SC-3930 - fix navigation error for import page

.mergify.yml
- the auto_merged label was applied wrongly to manually merged PRs when they had the ready to merge label but where merged manual
the label will now be set during the merge process, not afterwards
=> Quickfix - fix auto_merged label rules

src/serverMiddleware/routes.js, src/store/calendar.js
Should fix earlier cowboy-commits by Dr. Jan Renz which broke the integration tests in all repos 🤠
Here's the tl/dr: the integration tests which click around in the left menu fail if they click on a top-level nuxt page, since in nuxt, the links in the navigation bar don't have the `title` attribute. Until now, no top-level nuxt page was accessible in the navigation (content is behind a feature flag that the tests don't set yet). With https://github.com/hpi-schul-cloud/nuxt-client/commit/312ee52f60474efe1f4fde497ff993fd2105f176#diff-cbb87fee2982fe656d5592050d3605b9b320d91dd94fb3ffd8a1a02e70e3a91dR23, the content route was introduced without feature-flag, which broke the tests.
=> Quickfix - Remove content from routes, which causes tests to fail

CHANGELOG.md, locale/de.json, locale/en.json, package-lock.json, src/components/organisms/LernstoreDetailView.vue
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/SC-7447
Client: https://github.com/hpi-schul-cloud/schulcloud-client/compare/Feature/SC-7447-add-warning-text-leaving-sc?expand=1
Nuxt: https://github.com/hpi-schul-cloud/nuxt-client/compare/Feature/SC-7447-add-warning-text-leaving-sc?expand=1
The pr adds a warning text required by stake holders to warn users when they leave schul-cloud.
=> Feature/SC-7447 - add warning text leaving sc

CHANGELOG.md, src/components/molecules/AddContentModal.vue
fixes lernstore modal width
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7557
- changed as 300px width of the lernstore modal for adding content to 100%
=> SC-7557 - fixes lernstore modal width

CHANGELOG.md, src/pages/login-instances/index.vue
change tab name of login-instances page
- https://ticketsystem.schul-cloud.org/browse/SC-6992
=> SC-6992 - changed header name for login-instances page

CHANGELOG.md, locale/de.json, locale/en.json
Change the text from "created at" to "requested at".
In German: change from "erstellt am" to "abgerufen am".
- https://ticketsystem.schul-cloud.org/browse/SC-8433
=> SC-8433 - changed text in Lern-Store

CHANGELOG.md, package-lock.json, package.json, src/components/organisms/Ldap/LdapRolesSection.unit.js, src/components/organisms/Ldap/LdapRolesSection.vue
Fixes the client-side validation for the roles section
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8577
=> SC-8577 - hotfix/roles section validation fix

CHANGELOG.md, ansible/roles/nuxt-client/templates/deployment.yml.j2
Reduce resource consumption for deployed nuxtclient.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-37
https://ticketsystem.hpi-schul-cloud.org/browse/BC-56
Make CPU and memory resource consumption configurable.
Set the default for memory to be between 128mb and 4gb.
Set the default pod count to 1 pod
=> BC-37 - BC-56 - reduce resource consumption for deployed nuxtclient

ansible/roles/nuxt-client-core/tasks/main.yml
Change the mode for the configmaps at the ansible roles to apply for configmaps and secrets
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1230
hpi-schul-cloud/dof_app_deploy#111
hpi-schul-cloud/antivirus_check_service#20
hpi-schul-cloud/superhero-dashboard#157
hpi-schul-cloud/schulcloud-server#3311
hpi-schul-cloud/schulcloud-client#2759
hpi-schul-cloud/schulcloud-calendar#109
=> BC-1230 - change mode for configmaps to apply

vue3_poc/src/pages/HomePage.vue, vue3_poc/src/plugins/vuetify.ts, vue3_poc/src/styles/icons.ts
Adds a pattern to add custom icons in addition to vuetify's default @mdi.js icons.
https://ticketsystem.dbildungscloud.de/browse/BC-2378
=> BC-2378 - Custom Icon Libraries and MDI Icons

src/pages/RoomDetails.page.vue, src/pages/room-details.unit.ts
The new shareCourse-function needs to be hidden to the users as the new shared course import is not implemented yet.
That's why we need to introduce an additional feature toggle to be able to enable and disable the new and the old ShareCourse-Feature separately.
This PR 
- reroutes the "old" feature toggle FEATURE_COURSE_SHARE to the old share-flow
- reintroduces the replaced parts of the old share-flow
- handles the "new" feature toggle FEATURE_COURSE_SHARE_NEW to the new share-flow
https://ticketsystem.dbildungscloud.de/browse/BC-2570
=> BC-2570 - add feature toggle for new share course flow

locale/de.json, locale/en.json, locale/es.json, locale/ua.json, src/pages/administration/StudentOverview.page.vue, src/store/users.js, src/store/users.unit.js
When an administrator/teacher tries to send an email to an already registered user, the corresponding toast is displayed
- https://ticketsystem.dbildungscloud.de/browse/BC-2364
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2313
- toast with a message about an already registered user
- translations for toast
=> BC-2364 Display toast when trying to send mail to an already registered user

src/components/feature-board-file-element/FileContentElement.unit.ts, src/components/feature-board-file-element/FileContentElement.vue, src/components/feature-board-file-element/content/alert/useFileAlerts.composable.ts, src/components/feature-board-file-element/content/display/FileDisplay.unit.ts, src/components/feature-board-file-element/upload/FileUpload.unit.ts, src/components/feature-board-file-element/upload/FileUpload.vue, src/components/ui-alert/SuccessAlert.unit.ts
=> BC-5595 - Show progress bar

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/locales/uk.json
https://ticketsystem.dbildungscloud.de/browse/N21-1396
=> N21-1396 Change CTL label in boards

src/components/feature-board-file-element/upload/FileUpload.unit.ts, src/components/feature-board-file-element/upload/FileUpload.vue
=> BC-5074 - Confirm before page unload

src/components/feature-board/card/CardHost.vue
**Situation**:
The board sends several updateHeight-requests to the backend - whenever the height of card changes. 
Some of these changes are only temporary and should not trigger the update.
Some of those are evening triggered when e.g. a student surfes on the board.
**Fix**:
Only after finishing the editing of a card the current rendered height of the card is send via an updateHeight-request to the backend.
https://ticketsystem.dbildungscloud.de/browse/BC-4939
Internals of the CardHost-component
--
--
--
--
=> BC-4939 - fix update height

src/components/feature-board-text-element/RichTextContentElement.unit.ts, src/components/feature-board-text-element/RichTextContentElementDisplay.unit.ts, src/components/feature-board-text-element/RichTextContentElementEdit.unit.ts, src/components/feature-editor/CKEditor.unit.ts, src/components/feature-editor/CKEditor.vue
feature-board-text-element/RichTextContentElementDisplay.unit.ts
feature-board-text-element/RichTextContentElementEdit.unit.ts
feature-board-text-element/RichTextContentElement.unit.ts
feature-editor/CKEditor.unit.ts
BC-6175
=> BC-6175 - Vue3 upgrade: fix components/feature-board-text-element & /feature-editor tests

src/components/data-external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts, src/components/data-external-tool/ExternalToolLaunchState.composable.unit.ts
Because of the vue3 upgrade we need to refactor the following tests (src/components/data-external-tool):
data-external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
data-external-tool/ContextExternalToolApi.composable.unit.ts
data-external-tool/ExternalToolElementDisplayState.composable.unit.ts
data-external-tool/ExternalToolLaunchState.composable.unit.ts
data-external-tool/ExternalToolApi.composable.unit.ts
data-external-tool/SchoolExternalToolApi.composable.unit.ts
data-external-tool/SchoolExternalToolUsage.composable.unit.ts
BC-6165
=> BC-6165 - Vue3 upgrade: fix src/components/data-external-tool tests

src/components/feature-board-external-tool-element/ExternalToolElement.unit.ts, src/components/feature-board-external-tool-element/ExternalToolElement.vue, src/components/feature-board-external-tool-element/ExternalToolElementAlert.unit.ts, src/components/feature-board-external-tool-element/ExternalToolElementAlert.vue, src/components/feature-board-external-tool-element/ExternalToolElementConfigurationDialog.unit.ts, src/components/feature-board-external-tool-element/ExternalToolElementMenu.unit.ts
Fix src/components/feature-board-external-tool-element tests
BC-6171
=> BC-6171 -  Vue3 upgrade: fix src/components/feature-board-external-tool-element tests

src/components/molecules/vRoomGroupAvatar.vue
You can not reach the group avatar on course overview page via keyboard tabing, only the single courses.
BC-6512
=> BC-6512 - Vue3 upgrade: Fix room avatar access with keyboard

src/components/topbar/StatusAlerts.vue
Fix word break, contrast issues, icon opacity, alignment list items in status alerts
BC-6391
=> BC-6391 - status alerts (Bug Hunt Table 9)

src/components/data-board/BoardState.composable.ts, src/components/feature-board/card/CardHost.vue
a. when triggering the deletion of a card (e.g. via menu), the card is not properly removed
b. sometimes during deletion an error alert message is shown in the right top corner that something went wrong
the board is updated first, then the backend-api-call is executed
when trying to reproduce the error and a card that was deleted contained big files, the api-request took longer  then the default timeout for each request ([see also: question from Sergej](https://teamchat.dbildungscloud.de/group/DevOps-SRE-Open?msg=iqGDJJoQKfXXFd4nv) )... which resulted in a silent stop of the execution of the delete action, resulting in an not removed card. Only reload of the page or triggering the deletion again led to an update of the board.
good: the server executes the deletion till the end - even if …
=> BC-6391 - delete card error (Bughunt Vue3 | page 1 | bug #11)

src/components/page-board/ColumnBoard.page.vue, src/components/templates/DefaultWireframe.vue
The form to configure an external tool that should be added, was displayed with a scrollbar and the cancel and submit-button were not displayed completely (=cut off at the bottom).
BC-6611
- added property **allowOverflowX** to the DefaultWirframe and activated it for the CoulmBoard-page:
- **true**: menu-items of cards and columns outside of the screen (column 7+) are displayed with text
- **false**: no problems with unwanted scrollbars
- property set to true for ColumnBoard-Page
see the ticket
=> BC-6611 - wireframe layout scrollbar issue

.github/workflows/clean.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependabot-to-jira.yml, .github/workflows/dependency-review.yml, .github/workflows/push.yml, .github/workflows/security-audit.yml, .github/workflows/tag.yml, .github/workflows/test.yml, .github/workflows/test_unstable_e2e.yml
https://ticketsystem.dbildungscloud.de/browse/BC-6589
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4771
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3414
https://github.com/hpi-schul-cloud/nuxt-client/pull/3112
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/250
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/157
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/52
https://github.com/hpi-schul-cloud/version-aggregator/pull/19
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/798
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/9
https://github.com/hpi-schul-cloud/tldraw-client/pull/58
=> BC-6589 update gh-actions

src/serverApi/v3/api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-1887
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/255
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4978
=> N21-1887 Generate API

src/serverApi/v3/api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-1941
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5023
=> N21-1941 Bulk import for external tools

src/modules/data/board/boardActions/boardActionPayload.ts, src/modules/data/board/boardActions/boardActions.ts, src/modules/data/board/boardActions/boardSocketApi.composable.ts, src/modules/data/board/boardActions/boardSocketApi.composable.unit.ts, src/modules/data/board/cardActions/cardActionPayload.ts, src/modules/data/board/cardActions/cardSocketApi.composable.ts, src/modules/data/board/cardActions/cardSocketApi.composable.unit.ts
Simplify all Failure-Action payloads to no longer carry ErrorType and BoardNodeType in order simplify failure-structure and to remove redundancy between action-name and carried data. This way refactorings on the backend-side are enabled
https://ticketsystem.dbildungscloud.de/browse/BC-7298
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5041
=> BC-7298 - refactor failure actions

src/components/molecules/TaskItemMenu.vue, src/layouts/newLoggedIn.layout.vue, src/modules/ui/layout/sidebar/Sidebar.vue, src/modules/ui/layout/sidebar/SidebarCategoryItem.vue
- sidebar not scrollable on tablet with first touch/scroll (vue)
- scroll on main content not disabled, when sidebar is open (vue and legacy)
- scroll on task item more menu (in task overview) not possible when "edit" option is touched (vue)
BC-7415
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3457
(see Description)
=> BC-7415 - Make sidebar usable on tablets

src/components/rooms/RoomExternalToolCard.vue, src/modules/ui/chip/InfoChip.vue, src/modules/ui/chip/WarningChip.vue
Fixes incomplete operational chip. In template it was used the function reference instead of the function itself. Missing brackets "(" ")"
- https://ticketsystem.dbildungscloud.de/browse/N21-2021
=> N21-2021 fixes incomplete operational chip

src/modules/data/board/boardActions/boardActionPayload.ts, src/modules/data/board/boardActions/boardSocketApi.composable.ts, src/modules/data/board/boardActions/boardSocketApi.composable.unit.ts, src/modules/feature/board/card/CardHost.vue
Fixing two bugs that were introduced with the implementation of websocket-communication for boards:
**Problem 1**: 
When a new card gets created by clicking on the corresponding button, it gets created without an empty text field element.
**Problem 2**:
When the user hits enter key while being in a card title, a new text field element should be created at the beginning of the card and the cursor should jump into it.
BC-7583
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5086
=> BC-7583 - fix bugs in socket implementation

src/modules/feature/board-file-element/content/inputs/FileInputs.vue, src/modules/feature/board-file-element/content/inputs/alternative-text/AlternativeText.unit.ts, src/modules/feature/board-file-element/content/inputs/alternative-text/AlternativeText.vue, src/modules/feature/board-file-element/content/inputs/caption/CaptionText.unit.ts, src/modules/feature/board-file-element/content/inputs/caption/CaptionText.vue, src/modules/feature/board-text-element/RichTextContentElement.vue, src/modules/feature/board-text-element/RichTextContentElementEdit.unit.ts, src/modules/feature/board-text-element/RichTextContentElementEdit.vue, src/modules/feature/board/board/BoardColumnHeader.vue, src/modules/feature/board/card/CardHost.vue, src/modules/feature/board/card/CardTitle.vue, src/modules/feature/board/shared/BoardAnyTitleInput.unit.ts, src/modules/feature/board/shared/BoardAnyTitleInput.vue
During to some changes to fix problems from the migration to Vue3 - a wrong spacing over card titles was introduced and gets fixed with this PR.
BC-7588
=> BC-7588 - fix card title spacing

src/components/administration/ExternalToolSection.unit.ts, src/components/administration/ExternalToolSection.vue, src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/modules/data/external-tool/SchoolExternalToolApi.composable.unit.ts, src/serverApi/v3/api.ts, src/store/external-tool/mapper/school-external-tool.mapper.ts, src/store/external-tool/school-external-tool-metadata.ts, tests/test-utils/factory/schoolExternalToolMetadataFactory.ts, tests/test-utils/factory/schoolExternalToolMetadataResponseFactory.ts
when school admin deletes a school external tool, the tool usages from media shelf are also shown
- https://n21-2019-show-tool-usage.nbc.dbildungscloud.dev/administration/school-settings
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5071
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/257
=> N21-2019 show media shelf tool usages

src/modules/ui/board/content-element/ContentElementBar.unit.ts, src/modules/ui/board/content-element/ContentElementBar.vue, src/themes/brb/vuetify.options.ts, src/themes/n21/vuetify.options.ts, src/themes/thr/vuetify.options.ts, src/vuetify.options.ts
Add surface-light and on-surface-light variables in order to create a uniform design system according to Material Design principles.
BC-7168
=> BC-7168 Follow-up: Additions for a good working customized Material Design System

src/modules/data/board/cardActions/cardSocketApi.composable.ts
Implementation of basic load test capabilities.
BC-6854
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5099
=> BC-6854 - basic load tests

Dockerfile, src/modules/feature/media-shelf/data/mediaBoardState.composable.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2070
=> N21-2070 Prevent media shelf card from duplicating

config/webpack/webpack.common.js
In order to make sure that frontend application code is reloaded in the user's browser when it has been changed we want to enable Cache Busting.
Webpack builds can be configured to write a content hash in the generated file names during build. When the conten has been updated the hash will change and the browser is forced to reload the file.
https://webpack.js.org/guides/caching/
BC-8017
=> BC-8017 - Enable Cache Busting via Content Hash in Frontend

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/modules/feature/board-external-tool-element/ExternalToolElement.unit.ts, src/modules/feature/board-external-tool-element/ExternalToolElement.vue, tests/test-utils/factory/externalToolElementResponseFactory.ts, tests/test-utils/factory/index.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2148
=> N21-2148 Add aria-label to external tool element

src/serverApi/v3/api.ts
Updating the server API with `npm run generate-client:server`.
- <https://ticketsystem.dbildungscloud.de/browse/EW-1001>
- <https://github.com/hpi-schul-cloud/schulcloud-server/pull/5255>
=> EW-1001 Updating server api

src/serverApi/v3/api.ts
For the call to the authorization API of the schulcloud-server we want to generate an OpenAPI client and use it in the tldraw-server.
JIRA :
https://ticketsystem.dbildungscloud.de/browse/BC-7879
Links to deployments :
https://BC-7879-use-openapi-client-for-authz-calls.dbc.dbildungscloud.dev/
https://BC-7879-use-openapi-client-for-authz-calls.brb.dbildungscloud.dev/
https://BC-7879-use-openapi-client-for-authz-calls.nbc.dbildungscloud.dev/
Related PRs:
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5292
https://github.com/hpi-schul-cloud/tldraw-server/pull/22
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/994
=> BC-7879 - Use OpenAPI client for authz call in tldraw-server

src/serverApi/v3/api.ts
Users are not able to add members to a room, if the database contains schools that have no federalState defined.
BC-8746
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5443
* required property **federalState** for **schools** is now optional
=> BC-8746 - fix add members

src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
When joining or starting a video conference in specific browsers or devices (e.g. iPad or Safari) the newly created tab is blocked and specifically on the iPad there is no hint about it.
BC-8885
- implementing pre fetching join url
=> BC-8885 - Video conference opening in new tab is blocked by specific browsers and devices

src/modules/page/room/RoomMembers.page.vue, src/serverApi/v3/api.ts, src/store/env-config-defaults.ts
Currently the link behind "Further information" in the Room Member Administration page links to https://docs.dbildungscloud.de/display/SCDOK/Teameinladung+freigeben. This link needs to be replaced in all instances.
There is a different link for each instance, but it is the same for all languages.
BC-9509
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1152
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5643
- implementing separate room member info page for each instance
=> BC-9509 - Replace link to help article on Room Member Page

src/modules/feature/board-text-element/RichTextContentElement.vue
When selecting a table the selection frame and controls are slightly cut off. 
https://ticketsystem.dbildungscloud.de/browse/BC-9531
* position of buttons now inside the table
old
new
=> BC-9531 - table controls are cut off

src/components/molecules/CommonCartridgeExportModal.vue
Export dialog is now closed before export is started.
- https://ticketsystem.dbildungscloud.de/browse/EW-1180
=> EW-1180: Close dialog before starting export.

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts
On the LDAP config edit page, down below at "Klassen", the text states "Durch das Hinzufügen von zwei Semikolons können mehrere Nutzerpfade getrennt voneinander hinterlegt werden." but this doesn't seem to be correct.
BC-2344
- adjust config texts for ldap information regarding classes
=> BC-2344 - LDAP: Multiple class sources not possible

src/modules/feature/board-text-element/RichTextContentElement.unit.ts, src/modules/feature/board-text-element/RichTextContentElement.vue
After switching position (move up/down) of elements (e.g.tool and text) some ck-classes are missing, therefore different text styles are not displayed correctly e.g. headings.
https://ticketsystem.dbildungscloud.de/browse/BC-9968
move first-class logic to parent div
old
new
=> BC-9968 - Fix missing classes for text in boards
