components/card/card-footer-actions.vue, components/card/card-footer.vue, components/card/card-header-image.vue, components/card/card.vue, components/lib/pagination.vue, package-lock.json, package.json, pages/content/contentCard.vue, pages/content/index.vue
=> [WIP] Feature/LernStore

src/components/CourseCard.vue, src/pages/courses/index.vue
just a super simple grid, to play around
=> simple course index flex grid

_templates/new/component/doc.ejs.t, _templates/new/component/prompt.js, _templates/new/component/stories.ejs.t
Added template generation for storybook
=> Added template for component generation to add a story.

.github/issue_template.md, .github/pull_request_template.md
Some basic issue & pull request templates have been added to improve consistency.
=> #40 GitHub templates

compose-storybook-test.dummy
=> fix storybook deploy

docs/0-GettingStarted/README.md
quickfix for broken docs links
=> Update Broken Documentation Links

.travis.yml, Dockerfile.nuxt, README.md, _templates/new/component/stories.ejs.t, docs/0-GettingStarted/0-Development.md, docs/2-Tools.md, docs/CodeStyleguide.md, docs/components/base.md, docs/components/misc.md, docs/components/myButton.md, docs/storybook/README.md, docs/storybook/base.md, package.json, stories/base.stories.js, stories/misc.stories.js, yarn.lock
- Dashboard: https://codecov.io/gh/schul-cloud/nuxt-client
=> #24 add codecov tool

src/components/TemplateCourseWizard.vue, src/components/ui/BaseSelect.vue, stories/base.stories.js
Fixed some issues with the baseSelect in storybook
Added BaseInput type='time' to storybook
=> fixed css issue with select, added stories

.prettierignore, package.json
This fixes the build that broke with the commit https://github.com/schul-cloud/nuxt-client/commit/d10cb5c73049ace04f0fcd007da53d1fe3cc6537
=> Hotfix for introduced breaking changes

docs/.vuepress/config.js, docs/0-GettingStarted/0-Development.md, package.json
- unified port numbers to make it easier to remember
- **nuxt:** 4000
- **storybook:** 4001
- **docs:** 4002
=> unified ports

package.json, yarn.lock
Missing dependancy was breaking the build.
Added it with yarn.
=> Greenkeeper/nuxt 2.5.1

stories/.storybook/webpack.config.js
- storybook is now showing eslint errors
=> #123 - add eslint-loader to storybook config

docs/0-GettingStarted/README.md, docs/1-Tutorials/StorybookDokuErstellen.md, stories/CourseCard.stories.js, stories/base.stories.js
- Added some documentation for contribution to the internal storybook
=> Added storybook tutorial details.

.mergify.yml
=> mergify config cherry picked from #149

.mergify.yml, .travis.yml, README.md, deploy.sh, docs/0-GettingStarted/4-Workflow.md, docs/2-Tools.md
- Add some Description what the bot does, where it helps and what you need to do to use it :)
=> add mergify documentation

docs/.vuepress/config.js, docs/.vuepress/override.styl, docs/0-GettingStarted/0-Development.md, docs/0-GettingStarted/9-EditorSetup.md, docs/1-Tutorials/APIRequests.md, docs/1-Tutorials/StorybookDokuErstellen.md, docs/2-Tools.md
- Added Links to Repo and to Edit current Page
- updated theme color to schulcloud red
- added "new content" popup
- improved build speed by kicking out old browsers (https://vuepress.vuejs.org/config/#evergreen)
- some small documentation updates
=> some small theme changes

.mergify.yml, docs/2-Tools.md, docs/CodeStyleguide.md
Simplify the mergify config be removing an edge case for greenkeeper that wasn't even working due to branch protection rules.
=> simply mergify config and update documentation

src/components/CardFooter.vue, src/components/CourseCard.vue, src/components/CoursesGrid.vue, src/components/DropdownMenu.vue, src/components/MenuLink.vue, src/components/Pagination.vue, src/components/ProfilePicture.vue, src/components/PulsatingDot.vue, src/components/StepProgress.vue, src/components/TemplateTab.vue, src/components/TemplateTabs.vue, src/components/TheSidebar.vue, src/components/ui/BaseBlockquote.vue, src/components/ui/BaseBreadcrumb.vue, src/components/ui/BaseButton.vue, src/components/ui/BaseCollapsible.vue, src/components/ui/BaseDialog/BaseDialog.unit.js, src/components/ui/BaseDialog/BaseDialog.vue, src/components/ui/BaseIcon.vue, src/components/ui/BaseLink.vue, src/components/ui/BaseProgressbar.vue, src/components/ui/BaseSelect.vue, src/pages/content/index.vue, src/pages/index.vue
We discuessed this in a meeting a while ago with @rodebert and @ChrisWeissmann.
The component name is not required to be specififed and leaving it in may result in inconsistency after renaming a file. 
The name property is only required, when the component is defined recursivly
=> remove component names

docs/2-Styles/2-State-Style.md
- Adding some relevant documentation
=> State styles added as addressed in #127

.markdownlint.yml, .travis.yml, deploy/deploy.sh, docs/0-GettingStarted/1-Build.md, docs/2-Styles/0-Variables.md, docs/2-Styles/1-UtilityClasses.md, package.json
- moved api config from travis config to website and changed it to `https://api.test.schul-cloud.org`
- updated documentation
- hopefully fixed a docs deployment bug (variables not loaded)
=> Add real backend to deployment

docs/2-Styles/2-State-Style.md
The Method has not returned anything before
=> fix invalid docs example

package.json, yarn.lock
=> css loader downgrade

.mergify.yml, yarn.lock
- Adjusted config according to feedback
no ui change
=> Adjusted config according to feedback given by mergify support

docs/.vuepress/config.js, docs/.vuepress/styles/palette.styl, yarn.lock
- updated config according to migration guide at https://v1.vuepress.vuejs.org/miscellaneous/migration-guide.html#ga
-no ui changes
=> Adjusted vuepress config according to migration guide

docs/storybook/typography.md, src/themes/default/styles/utility/_typography.scss, src/themes/default/styles/variables/_typography.scss, stories/typography.stories.js
- Adjusted Font Variables according to the new specs
=> new font size variables

.travis.yml
Update travis config to run deploy script always, deploy script decides
=> updated travis config

.travis.yml, README.md, deploy/compose-nuxt.dummy, deploy/deploy.sh, docs/0-GettingStarted/0-Development.md, docs/4-Tools.md
=> Updating stable

deploy/deploy.sh
=> added docker credentials

src/components/PopupIconInitials.vue, src/components/TheTopBar.vue
=> forgot to push (top and sidebar)

src/themes/default/styles/utility/_typography.scss
=> change font-weight for headlines to normal

docs/0-GettingStarted/0-Development.md
http://docs.273.nuxt.schul-cloud.surge.sh/0-GettingStarted/0-Development.html#setup
=> adjust setup docs

package-lock.json, package.json
=> Greenkeeper/vuepress 1.1.0

src/components/TheFooter.unit.js, src/components/TheFooter.vue, src/store/auth.js, src/utils/documents.js
- Adapted footer styling to legacy client
- Added link to privacy document for model schools
=> VUE-74 - Footer from legacy client

deploy/compose-client.dummy, docs/0-GettingStarted/1-Build.md, nuxt.config.js, package-lock.json, package.json, sentry.config.js, src/plugins/sentry.js
=> add sentry error logging

.travis.yml
- build all themes on travis to be sure all are working
=> Build All Themes on Travis

.eslintignore, .prettierignore, .stylelintignore, docs/1-Tutorials/Localization.md, locale/de.json, locale/en.json, src/pages/impressum.vue
=> repair i18n

docs/storybook/molecules/FloatingFab.md, src/components/atoms/PulsatingDot.stories.js, src/components/base/BaseButton.vue, src/components/base/BaseGrid.stories.js, src/components/base/BaseGrid.vue, src/components/base/BaseIcon.vue, src/components/base/BaseTextarea.stories.js, src/components/base/BaseTitle.stories.js, src/components/molecules/CourseCard/index.vue, src/components/molecules/FloatingFab.stories.js, src/components/molecules/FloatingFab.unit.js, src/components/molecules/FloatingFab.vue, src/components/molecules/Searchbar.stories.js, src/layouts/default.vue, src/pages/content/index.vue, src/pages/courses/create.vue, src/pages/courses/index.vue, src/pages/news/_id/edit.vue, src/pages/news/_id/index.vue, src/pages/news/index.vue, src/pages/news/new.vue, src/pages/nuxtversion.vue, src/pages/teams/index.vue, src/themes/default/styles/variables/_layers.scss, stories/CourseCard.stories.js, stories/Onboarding.stories.js, stories/ProgressRing.stories.js, stories/base.stories.js, stories/misc.stories.js
- Adding a simple fab button
- icon changeable
- position changeable 
- storybook cleanup
=> Simple FAB button

src/components/base/BaseBreadcrumb.vue
- adjust padding left & right to have it lined up with the page (it's now 0)
- changed the cursor on the last element to the default cursor because it's not clickable
=> cherrypick from #351 and #353

src/components/base/BaseButton.unit.js, src/components/base/BaseButton.vue
- cherrypick from #301 
- the default type wasn't set anymore, therefore all buttons where by default submit buttons
- fixed issue
- added some tests to prevent this error in the future
=> button hotfix from #301

src/components/organisms/Tabs/Tabs.vue
=> select first Tab if no selection predefined

_templates/new/component/doc.ejs.t, _templates/new/component/prompt.js, _templates/new/component/stories.ejs.t
- cherrypick from #350
- the markdown file for storybook notes is now optional
- storybook file is now placed next to the component itself
=> improve storybook template

.vscode/settings.json
=> add prettier paths to config

src/layouts/legacyLoggedIn.vue
fullscreen mode now works properly
=> fixing fullscreen mode

src/layouts/legacyLoggedIn.vue
=> removed duplicate line of code

src/pages/courses/index.vue, src/pages/news/index.vue
just wrapped fab buttons in base-link on news and course index
=> changed link handling fab button

src/components/base/BaseContentContainer.stories.js, src/components/base/BaseContentContainer.unit.js, src/components/base/BaseContentContainer.vue, src/layouts/loggedInFull.vue, src/themes/default/styles/variables/_breakpoints.scss
- #353 new full width layout for overview pages (we currently don't have any)
=> add full width layout

docs/storybook/helpers/RenderHtml.md, src/components/helpers/RenderHtml.stories.js, src/components/helpers/RenderHtml.unit.js, src/components/helpers/RenderHtml.vue, stories/UserHas.stories.js
- This component can take in some html and render all the defined vue-components in it.
- Check the Storybook entry for more details. Especially the notes ;)
=> add RenderHtml Component

docs/0-GettingStarted/1-Build.md
There where some wrong default values in the docs
- updated them
=> Update default values

src/components/base/BaseInput/BaseInput.stories.js, src/components/base/BaseInput/BaseInput.vue
- add a bit bottom margin to add space between mulitple inputs
- added some example stories for these cases
=> add margin bottom to  inputs

src/components/base/BaseInput/BaseInput.stories.js, src/components/base/BaseInput/BaseInputCalendar.vue
- removed border of date picker
- added date picker to storybook
=> remove border from date picker

README.md
- added urls + badges for most deployed instances
- skipped themed versions for now
=> add badges for deployments

src/components/base/BaseButton.scss, src/themes/default/styles/utility.scss
General (if not overwritten by component):
Buttons, see http://stories.383.nuxt.schul-cloud.surge.sh:
=> adapted focus styles for buttons and general elements

src/serverMiddleware/routes.js
The News details page is unfinished and not ready for release. => disable it for now
=> disable news detail page

locale/de.json, package-lock.json, package.json, src/components/base/BaseDialog/BaseDialog.stories.js, src/components/base/BaseDialog/BaseDialog.unit.js, src/components/base/BaseDialog/BaseDialog.vue, src/components/base/BaseDialog/index.unit.js, src/components/base/BaseModal.stories.js, src/components/molecules/ModalBodyInfo.vue, src/themes/default/styles/utility/_typography.scss, stories/base.stories.js, tests/unit/setup.js
- refactored BaseDialog to use BaseModal and our new styles
- ~I was unable to write any meaningfull test. I have no idea how to deal with this. If anyone has any idea, please help me!~ Done, except for the auto mount to body.
=> Add BaseDialog Confirm

src/pages/courses/_id/index.vue, src/store/course-groups.js, src/store/homeworks.js, src/store/lessons.js
Preparations for new course view
adding service templates for lessons, groups, homeworks
retrieving data in course
-
=> Getting store data in Course View

.vscode/settings.json
With VSCode 1.41 some settings options need some refactoring, which will mostly be done automaticaly. This is just the checkin of these required changes.
- removed/replaced deprecated attributes
- use recommended short syntax for eslint validation config
- **No configuration will be changed by this pull**
=> cleanup vscode config

.travis.yml
=> apply falcos changes from ops247 to a new fresh branch

src/themes/default/styles/utility/_spacing.scss
=> removed !important statements from margins

.eslintrc.js, src/components/base/BaseLink.unit.js, src/components/legacy/MenuQrCode.unit.js, src/components/molecules/MintEcFooter.vue, src/components/molecules/TextEditor.unit.js, src/components/organisms/CourseWizard/StepData.unit.js, src/components/organisms/FormNews.unit.js, src/plugins/authenticate.unit.js
- enables the `jest/prefer-spy-on rule` lint rule and fixes upcoming issues
**Why?**
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/prefer-spy-on.md
=> enable jest/prefer-spy-on rule

package-lock.json, package.json
=> update nodesass to fix security audit

src/components/base/BaseDialog/BaseDialog.vue, src/components/base/BaseInput/BaseInput.stories.js, src/components/base/BaseInput/BaseInput.unit.js, src/components/base/BaseInput/BaseInput.vue, src/components/base/BaseModal.stories.js, src/components/base/BaseTextarea.vue, src/components/molecules/NewsCard.vue, src/pages/schools.vue, src/pages/teams/index.vue, tests/unit/commonTests.js
=> convert all slots to new syntax

README.md
=> add lokalise badge

jest.config.js, package.json, src/components/molecules/ContextMenu.unit.js, src/components/molecules/ContextMenu.vue, tests/unit/requireAssertions.js
- this change requires all test cases to have at least one expect to actually test something
- fixed some tests that were violating this rule
=> require tests to test something

src/components/organisms/DataTable/TableHeadRow.vue
=> SC-3435 - Vertical Center Sort Icon

src/themes/default/styles/utility/_typography.scss, src/themes/default/styles/variables/_typography.scss, stories/typography.stories.js
=> Design System h5, h6 bold, change in line-height-sm, story for line-heights

stories/DesignTokens.stories.js
=> added spacings to design tokens in storybook

locale/de.json, src/pages/administration/students.vue
=> add add_student fab

src/pages/administration/students.vue
=> bugfix praseInt for localStorage get

src/store/users.js
- plainly added a store action to users, to retrieve all teachers on the teachers admin page
=> added findTeachers fct to users store

src/components/organisms/FormNews.unit.js
- fixing test, which is failing due to DST
=> [Fix] test; failing due to daylight saving time

docs/1-Tutorials/ExpendableForm.md
=> docs: tutorial "Expendable Form"

package-lock.json, package.json, stories/.storybook/main.js, stories/.storybook/manager.js, stories/.storybook/preview.js, stories/.storybook/theme.js
closes #140 
- the storybook got some fonts and colors 💘
=> #140 storybook theme 

src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
=> changed import icon

src/components/organisms/FormCreateUser.vue
- skip roles fetch before post
=> skip role fetch for user create

locale/de.json, src/components/molecules/AdminTableLegend.vue
- updated admintable sync hint
=> SC-3877 | updated admintable sync hint

.eslintrc.js
- rule is not needed anymore
- depends on #941
=> Quickfix - remove outdated lint rule

jest.config.js
some directories with tests where not included in the coverage report. Now they are :D
=> Quickfix - collect coverage of more directories

src/components/organisms/DataFilter/DataFilterChips.vue
=> SC-3513 - Filter chips fixed on mobile devices

src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
https://github.com/schul-cloud/schulcloud-server/pull/1286
=> SC-3513 - sorting by classes and consent

.github/workflows/test.yml
Change the Github action to work with secrets and auth for priv repos.
https://ticketsystem.schul-cloud.org/browse/OPS-610
Github action workflo for integration tast.
=> OPS-610 - Github actions for test edit

.github/workflows/pr-automation-comment-reaction.yml
=> Quickfix - Update pr-automation-comment-reaction.yml

.github/workflows/pr-automation-auto-approve.yml
- Dependabot PRs need to be auto approved
=> Quickfix - Create pr-automation-auto-approve.yml

src/components/legacy/NavigationBar.vue, src/utils/navbarBaseItems.js
- https://github.com/schul-cloud/schulcloud-server/pull/????
- https://ticketsystem.schul-cloud.org/browse/SC-5201
=> SC-5201 - fix-navbar-items

.github/workflows/pr-automation-auto-approve.yml
=> Update pr-automation-auto-approve.yml with SC-Bot-Token

.github/workflows/test.yml
by only executing npm run lint on one failed ci server (ubuntu). The step had not added any value, because the commit step afterwards already has the newly added restriction.
=> Quickfix - save some ci time

.github/workflows/update_version.yml
https://ticketsystem.schul-cloud.org/browse/OPS-737
Details are in the ticket
The filter was checked in the repository https://github.com/dimapin/github-actions-playground
=> OPS-737 - Fixed the filter logic on create trigger

src/components/molecules/NotificationModal.stories.js, src/components/molecules/NotificationModal.unit.js, src/components/molecules/NotificationModal.vue, src/components/organisms/AddContentButton.vue
adjusted to new changes from https://github.com/schul-cloud/nuxt-client/pull/1081
- https://github.com/schul-cloud/nuxt-client/pull/1081
- https://ticketsystem.schul-cloud.org/browse/SC-5354
=> SC-5354 - adjusted-NotificationModal-to-get-any-color

src/components/organisms/LernstoreDetailView.vue
tab name in LernStore for DetailView
- https://github.com/schul-cloud/schulcloud-server/pull/????
- https://ticketsystem.schul-cloud.org/browse/SC-5478
=> SC-5478 - fix-tab-name

package.json
Fix the lodash version to 4.17.15 since the newer ones are missing a package
=> rollback and fix lodash to version 4.17.15

package-lock.json, src/components/legacy/NavigationBar.stories.js, src/components/legacy/NavigationBar.unit.js, src/utils/navbarBaseItems.js
Changed link in the navigation bar
Related to PR https://github.com/schul-cloud/schulcloud-client/pull/1994 in the schulcloud-client
Base links to copy
- https://ticketsystem.schul-cloud.org/browse/SC-5494
Replaced old link with: https://blog.schul-cloud.org/erste-schritte/
=> SC-5494 - Changed link in navigation bar

src/components/molecules/ModalFooterConfirm.vue, src/components/molecules/NotificationModal.vue, src/components/organisms/AddContentButton.vue
need to fix color on hover, there is always green on hover, regardless Success or not
- https://ticketsystem.schul-cloud.org/browse/SC-5517
=> SC-5517 - hover-bug

src/themes/brb/styles/variables.scss, src/themes/open/styles/variables.scss, src/themes/thr/styles/variables.scss
=> SC-5486 - fixing the font scaling issue for the themes

src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
Change the default number of displayed elements in admin table to 25
=> SC-5535 - Change default limit to 25

deploy/compose-client_default.dummy
added content security policy (csp) environment variables to docker compose file.
[https://ticketsystem.schul-cloud.org/browse/SC-4717](https://ticketsystem.schul-cloud.org/browse/SC-4717)
=> SC-4717 - CSP Envs

src/pages/administration/students/index.vue
https://ticketsystem.schul-cloud.org/browse/SC-5538
=> SC-5538 - Refresh users table after deleting the user

src/serverMiddleware/routes.js
Add `/content/redirect` as exception for the router 
https://ticketsystem.schul-cloud.org/browse/SC-5802
=> SC-5802 add content/redirect as exception for the router

src/components/molecules/ContentSearchbar.vue
=> SC-5812 - fix request pollution

src/components/organisms/FormCreateUser.vue
Quickfix uncheck registrierunglink by default
Origin ticket: https://ticketsystem.schul-cloud.org/browse/SC-5938
Subtask of: https://ticketsystem.schul-cloud.org/browse/SC-3515
=> SC-5938 - Quickfix uncheck registrierunglink by default

src/components/molecules/ContentSearchbar.vue
=> Quickfix - increase threshold for search

src/pages/administration/teachers/index.vue
Added isExternal check to icon and hint text.
=> SC-6324 - quickfix add isExternal check to icon and hint

src/pages/administration/teachers/index.vue
Fix to external school legend is not shown and user creation is allowed for external schools in teacher admin tables.
https://ticketsystem.schul-cloud.org/browse/SC-6587
=> SC-6587 - quickfix - teachers table external school checks

src/pages/administration/students/index.vue
Restored birth date column in students table
https://ticketsystem.schul-cloud.org/browse/SC-6600
=> SC-6600 - quickfix restore birth date column

locale/de.json, src/components/legacy/TheTopBar.unit.js, src/components/legacy/TheTopBar.vue
change wording Abmelden to Logout
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6632
=> SC-6632 - change wording Abmelden to Logout

locale/de.json, src/utils/adminFilter.js
Changed filter names for teachers table
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6667
=> SC-6667 - quickfix filter name for teachers table

CHANGELOG.md, package-lock.json, package.json, src/store/ghost.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6701
=> SC-6701 - mint-ec URL (Hotfix 24.4.1)

src/components/legacy/TheSidebar.vue
sidebar test IDs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6704
=> SC-6704 - sidebar test IDs

deploy/deploy.sh
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1109
Remove automatic deployment on test environment. Replaced by sc-app-ci GitHub action.
=> OPS-1109 - removed deployment on testenvironment.

src/components/base/BaseInput/BaseInputDefault.vue, src/pages/administration/students/consent.vue, src/pages/administration/students/new.vue
Set limits and pattern validation to calendar input
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6603
=> SC-6603 - set limits and pattern to calendar input

src/pages/administration/teachers/index.vue
Removed analogue consent action for teachers
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6779
=> SC-6779 - quickfix - remove analogue consent action

src/pages/administration/students/consent.vue
Changed query parameter to fit the server requirements
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6743
=> SC-6743 - quickfix/change query parameter

src/pages/administration/students/consent.vue
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6775
- Adjusting style layouts
=> SC-6775-Quickfix-layout issue with birthdate line inside analogue consent part	

src/pages/content/index.vue
added data-testid for qa team in lernstore 
- https://ticketsystem.schul-cloud.org/browse/SC-6808
=> SC-6808 - added testid for qa team to test lernstore

src/pages/administration/teachers/index.vue
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6839
- uiState is corrected
=> SC-6839-Quickfix-search input from search bar entered in students table is taken over to teachers table

src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6843
- Searchbar text trimmed.
=> SC-6843-Quickfix-Trim white spaces in the searchbar text

src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
The error message was hardcoded and shown even if the action was successfully dispatched
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6860
=> SC-6860 - quickfix-remove qr error message

locale/en.json, src/components/molecules/EmptyState.vue
v-html in empty state
- https://ticketsystem.schul-cloud.org/browse/SC-6836
=> SC-6836 - html lang value

docs/1-Tutorials/APIRequests.md
In the architecture review we found misusage of the vuex store. Hopefully that will be less, if it is explained better in the documentation.
Docs only
=> Quickfix - Update docs regarding the store usage

CHANGELOG.md, package-lock.json, package.json
=> updated package, package-lock, changelog

CHANGELOG.md, src/components/organisms/DataTable/BackendDataTable.vue, src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
Removed trigger of update page on changing the limit
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6357
=> SC-6357 - prevent double loading

CHANGELOG.md, package-lock.json, package.json
=> hotfix/1/SC-6932 - version bump

CHANGELOG.md, locale/de.json, locale/en.json, src/utils/sidebarBaseItems.js
The Help and Verwaltung items were missing in sidebar, when in nuxt
- https://ticketsystem.schul-cloud.org/browse/SC-6549
=> SC-6549 - fix missing sidebar items

CHANGELOG.md, src/pages/content/_id/index.vue, src/pages/content/index.vue, src/store/auth.js, src/utils/sidebarBaseItems.js
[SC-6293](https://ticketsystem.hpi-schul-cloud.org/browse/SC-6293)
https://github.com/hpi-schul-cloud/schulcloud-server/pull/1864
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2280
- restricts Lern-Store access by new permission LERNSTORE_VIEW
- store auth, now loads full permissions for user, e.g. school permission too, not just the ones on his role. 
Sometimes, we can have permissions defined on schools, which can overwrite the ones from the role. This was not working in nuxt. The fix is simply doing the same we do in [client](https://github.com/hpi-schul-cloud/schulcloud-client/blob/develop/helpers/authentication.js#L118), thus also keeping it consistent. 
More and detailed …
=> SC-6293 - restricts Lern-Store with permission

CHANGELOG.md, locale/de.json, locale/en.json, package.json, src/components/organisms/LernstoreDetailView.vue
Conditional rendering of information when logged in through brandenburg
Hotfix. more info coming
=> Hotfix/5/SC-7447 - leave text

src/store/auth.js
the roles/user route is opened, and we can enable again its usage which was temporarly removed in this [commit](https://github.com/hpi-schul-cloud/nuxt-client/pull/1471/commits/fd7a5959667455cc590458a14d06b5c364dc09fc)
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7482
=> SC-7482 - enable loading of route

src/plugins/datetime.js, tests/plugins/datetime.unit.js
=> Bugfix/SC-2710 - fix test tz

package-lock.json, package.json
=> Quickfix - Updated package "@tryghost/content-api"

CHANGELOG.md, src/pages/administration/ldap/ldap-config.vue
Added ADMIN_VIEW and SCHOOL_EDIT permission to check to the ldap config page
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7798
=> SC-7798 - add permission check to ldap-config

CHANGELOG.md, locale/de.json, src/components/organisms/Ldap/LdapClassesSection.vue, src/pages/administration/ldap/config.vue
Add custom event to clear classes inputs when the toggle is off
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8169
=> SC-8169 - classes section clear inputs event

CHANGELOG.md, src/pages/administration/students/consent.vue, src/plugins/datetime.js, src/store/bulkConsent.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8219
- Adding a function in datetime.js file and some code-refactoring
=> Feature/SC-8219 - Datetime correction on students consent page

src/components/organisms/ContentCard.unit.js, src/components/organisms/LernstoreCollectionDetailView.unit.js, src/components/organisms/LernstoreCollectionDetailView.vue
Writes unit tests for collections feature
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8094
Adds unit tests to ContentCard and LernstoreCollectionDetailView components
=> SC-8094 - writes unit tests for collections feature

CHANGELOG.md, src/components/templates/CommonTermsOfUse.vue
I more address to change
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7824
=> SC-7824 - changed address in the Common Terms Of Use

.github/workflows/test.yml, CHANGELOG.md
This PR introduces authenticating against docker hub requests for end-to-end tests github action, while it was already optionally added in integration tests.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8356
=> SC-8356 - authenticate docker hub requests

CHANGELOG.md, package-lock.json, package.json, src/pages/content/index.vue
Adds a delay in the Lern-Store search.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8454
=> SC-8454 - delay search

.github/workflows/main.yml, k8s/configmap.yaml, k8s/ingress.yaml
=> Kubectls experiments ssl

package-lock.json, package.json
Version fix 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8600
=> SC-8600 - fix version

CHANGELOG.md, locale/de.json, locale/en.json, package-lock.json, package.json, src/pages/administration/ldap/activate.vue, src/pages/administration/ldap/config.vue, src/store/ldap-config.js, src/store/ldap-config.unit.js
Reverts hpi-schul-cloud/nuxt-client#1665
=> Revert "SC-8613 - LDAP-config-verify: Add checkbox to choose full or partial lo…"

CHANGELOG.md, src/components/organisms/AddContentButton.vue, src/components/organisms/ContentCard.vue, src/components/organisms/LernstoreDetailView.vue, src/pages/content/index.vue, stories/mockData/Resource.js
DO NOT MERGE without the server PR
Uses a different field for edu-sharing nodes, which is persisted so that recrawling won't change the URL to the lern-store item details  page anymore.
Adds a link to collection from item detail page.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7944
https://github.com/hpi-schul-cloud/schulcloud-server/pull/2263
=> SC-7944 - changes field for Lern-Store content id; adds a link to collection

CHANGELOG.md, src/components/molecules/AdminTableLegend.vue, src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
removed consent column and legend for external schools
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8681
=> SC-8681 - remove consent column

CHANGELOG.md, src/components/organisms/DataTable/BackendDataTable.unit.js, src/components/organisms/DataTable/DataTable.unit.js, src/components/organisms/DataTable/RowSelectionBar.vue
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8702
=> SC-8702 - disable the select all button

CHANGELOG.md, locale/de.json, locale/en.json, locale/es.json, package-lock.json, package.json
- https://ticketsystem.schul-cloud.org/browse/SC-8822
- added availability to phone numbers
- n21/nbr deployment  unneeded
=> SC-8822 - add availability to phone number in imprint

locale/de.json
There was a simple spelling mistake in the NAT "Lehrkraäfte importieren" instead of "Lehrkräfte importieren" 
https://ticketsystem.schul-cloud.org/browse/SC-8791
fix the simple spelling mistake
=> SC-8791 - fix spelling mistake in NAT

CHANGELOG.md, src/utils/adminFilter.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8708
=> SC-8708 - remove last and first name filter

CHANGELOG.md, package-lock.json, package.json, src/components/organisms/FormNews.unit.js, src/components/organisms/FormNews.vue, src/plugins/datetime.js, tests/plugins/datetime.unit.js
Fix timezone issues
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8837
=> SC-8837 - fix timezone issues in datetime.js

CHANGELOG.md, src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
added an external check for the delete action
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8910
=> SC-8910 - add external check for delete action

CHANGELOG.md, src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue
fixes some titles
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8916
=> SC-8916 - fixes some titltes

CHANGELOG.md, src/pages/administration/students/index.vue
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8681
=> SC-8681 - consent fix

package.json, stories/.storybook/main.js
Removing storybook addon, to make storybook work again, before we upgrade to new version 
=> Quickfix - Storybook: remove addon backgrounds which breaks storybook in this version

locale/de.json, locale/en.json, locale/es.json, src/components/organisms/HomeworksList.unit.js, src/components/organisms/HomeworksList.vue, src/plugins/datetime.js, stories/mockData/Homeworks.js, tests/plugins/datetime.unit.js
User story
As a student, I want to see the duedates of my tasks in the homeworks dashboard
Acceptance criteria
GIVEN I am logged in as student
WHEN I visit the homeworks dashboard
THEN I see the correct duedate for each of the homeworks
GIVEN I am logged in as student
WHEN I visit the homeworks dashboard
THEN I see the correct translation for the duedate-text
GIVEN I am logged in as student
WHEN I visit the homeworks dashboard
WHEN I have a homework without duedate
THEN I see that this homework does not have a duedate
GIVEN I am logged in as student
WHEN I visit the homeworks dashboard
WHEN I have a homework that is overdue
THEN I see a hint that it's not possible to hand in anymore
=> SC-9026 Show duedates in homeworks dashboard [Odyssey]

.vscode/launch.json, CHANGELOG.md, src/components/organisms/DatasourceRunWebuntis.vue, src/components/organisms/FormDatasourceLogin.unit.js, src/components/organisms/FormDatasourceLogin.vue, src/components/organisms/FormNews.vue, src/pages/activation/_activationCode/index.vue, src/pages/administration/datasources/_datasource/run/_run.vue, src/pages/administration/datasources/index.vue, src/pages/administration/datasources/new.vue, src/pages/administration/datasources/webuntis/_id/edit.vue, src/pages/administration/students/index.vue, src/pages/administration/teachers/index.vue, src/pages/mint-ec/_article.vue, src/store/ghost.js, src/store/users.js, src/store/users.unit.js, src/store/webuntis-metadata.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9077
=> SC-9077 - store/use of store refactoring

.vscode/launch.json, src/store/homeworks.js, src/utils/fetchAll.js, src/utils/fetchAll.unit.js, src/utils/index.js
=> Add fetchAll util for get paginated resources from api

src/store/homeworks.unit.js, stories/mockData/Homeworks.js
- wrote unit tests for the getters in homeworks store
- refactored mock data, so we can access open homeworks, overdue homeworks etc. in our tests
=> Wrote unit tests for the getters in homeworks.js and refactored mock data.

CHANGELOG.md, deploy/Dockerfile.client, deploy/build.sh, package-lock.json, package.json
the SC_THEME was not passed to the docker build
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9144
=> SC-9144 - fixed build with env SC_THEME

CHANGELOG.md, src/components/helpers/UserHasPermission.unit.js, src/components/helpers/UserHasRole.unit.js, src/components/helpers/UserHasRole.vue, src/components/legacy/UserRole.unit.js, src/components/legacy/UserRole.vue, src/components/molecules/AddContentModal.unit.js, src/components/molecules/AddContentModal.vue, src/layouts/legacyLoggedIn.vue, src/middleware/externally-managed-check.js, src/mixins/UserHasPermission.js, src/pages/administration/students/index.unit.js, src/pages/administration/students/index.vue, src/pages/administration/teachers/index.unit.js, src/pages/administration/teachers/index.vue, src/store/auth.js, src/store/courses.js, tests/middleware/externally-managed-check.unit.js
Moved getters logic from components to the store
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9122
=> SC-9122 - getters logic

CHANGELOG.md, src/components/organisms/FormNews.vue, src/utils/service-template.js
Fixed getStatus getter access the wrong state object
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9160
=> SC-9160 - fix getStatus getter

CHANGELOG.md, src/pages/administration/students/consent.unit.js, src/pages/administration/students/consent.vue, src/store/bulkConsent.js, src/store/users.unit.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9131
- Password changing feature is fixed
=> Feature/SC-9131 - fixing password changing on student consent page

CHANGELOG.md, ansible/roles/nuxt-client/templates/configmap.yml.j2, src/serverMiddleware/routes.js
=> change default lernstore mode to edusharing

CHANGELOG.md, package-lock.json, package.json, src/pages/administration/students/new.vue, src/pages/administration/teachers/new.vue
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9215
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9215
=> SC-9215 remove misbehaving checkbox

CHANGELOG.md, src/components/molecules/vCustomDoublePanels.unit.js, src/components/molecules/vCustomDoublePanels.vue, src/components/organisms/HomeworksDashboardStudent.vue, src/components/organisms/HomeworksDashboardTeacher.vue
- panels are now not only expansive, but also collapsible once clicked
This Pull-Request template helps the reviewers as well as servers as a checklist for you. Please feel out all possible sections.
Quality guidelines:
- Code should be self-explanatory; Document code that is not self-explanatory
- Code respects SOLID principles, DRY, YAGNI, KISS
- Think about potential bugs this Pull Request might introduce
- Keep security in mind
- Write tests (Unit and Integration), including for error cases. Don't decrease coverage
- Business logic should be implemented in the API; never trust the client
- UI changes should be discussed & agreed with the UX-Team before staring
- Keep the CHANGELOG up-to-date
- Boyscout rule: leave the code in a better state than you found it. Remove unnecessary lines. …
=> SC-9217 toggle() in vCustomDoublePanels

CHANGELOG.md, locale/de.json, locale/en.json, locale/es.json, src/components/templates/impressum.vue, src/themes/brb/components/templates/impressum.vue, src/themes/n21/components/templates/impressum.vue, src/themes/open/templates/impressum.vue, src/themes/thr/components/templates/impressum.vue
Changed contact data in imprint (phone and fax number were removed) and updated email address for brb.
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/11
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2622
- https://ticketsystem.schul-cloud.org/browse/SC-9221
**BEFORE:**
**AFTER:**
=> SC-9221 changed contact data in imprint

CHANGELOG.md, src/utils/adminFilter.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9175
- The old and future classes are removed from the class filter
=> SC-9175 removing old and future classes from class filter

.github/workflows/test_e2e.yml, CHANGELOG.md
This PR aligns e2e test execution to SC-9191 to how it works currently for the server repo.
Tests will be triggered on label change 'run tests' not only on commits after the label has been set.
=> SC-9191 run e2e tests in pull requests with 'run tests' label

CHANGELOG.md, nuxt.config.js, package-lock.json, package.json, src/components/organisms/AddContentButton.vue, src/components/organisms/LernstoreDetailView.vue, src/pages/TermsOfUse.vue, src/plugins/axios.js, src/store/accounts.js, src/store/activation.js, src/store/auth.js, src/store/bulkConsent.js, src/store/calendar.js, src/store/content.js, src/store/env-config.js, src/store/env-config.unit.js, src/store/insights.js, src/store/ldap-config.js, src/store/ldap-config.unit.js, src/store/messenger.js, src/store/messenger.unit.js, src/store/news.ts, src/store/news.unit.ts, src/store/teams.js, src/store/terms-and-conditions.js, src/store/users.js, src/store/users.unit.js, src/store/webuntis-metadata.js, src/utils/service-template.js
Access feathers and NestJS apps by their verision prefixes.
=> SC-9192 Fix path mapping

CHANGELOG.md, package-lock.json, package.json, src/store/content.js, src/store/ldap-config.js, src/store/ldap-config.unit.js
This PR brings back the following functionalities which have been broken in 26.9.0:
- load existing ldap config 
- add material to a courses lesson
=> SC-9192 BC-69 add path versions in axios requests

.github/workflows/test_e2e_pull_request.yml, .github/workflows/test_e2e_push_main.yml, CHANGELOG.md
This PR adds a new action which checks e2e tests for push on main branch.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-67
=> BC-64 BC-67 execute e2e tests for push on main

CHANGELOG.md, src/themes/thr/components/legacy/TheFooter.vue
Changed contact address in footer for thuringia theme.
Removed © in footer for thuringia theme.
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-14
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2652
=> BC-14-changed thr contact address

.dockerignore, Dockerfile.client, docs/0-GettingStarted/1-Build.md, startup.sh
bc-36 improved nuxt container image
=> bc-36 improved nuxt container image

CHANGELOG.md, src/components/organisms/administration/GeneralSettings.unit.js, src/components/organisms/administration/GeneralSettings.vue, src/pages/administration/school-settings.vue, src/store/schools.js, src/store/schools.unit.js
https://ticketsystem.hpi-schul-cloud.org/browse/BC-190
- fileStorageData usage is deleted on school settings page
=> feature/BC-190 - removing dataStorage

CHANGELOG.md, src/store/auth.js, src/store/roles.js
The hasRole action from the auth module is unused, and because the roles store module was only being used there, it has also been removed.
=> BC-201 - hasRole action and roles module cleanup

.eslintrc.js, CHANGELOG.md
added no-focused-tests eslint rule
https://ticketsystem.hpi-schul-cloud.org/browse/BC-136
=> BC-136 - add no-focused-tests eslint rule

src/components/atoms/vCustomAutocomplete.vue, src/components/molecules/vCustomDoublePanels.vue, src/components/molecules/vHomeworkItemTeacher.vue, src/components/organisms/HomeworksDashboardMain.unit.js, src/components/organisms/HomeworksDashboardMain.vue, src/components/organisms/HomeworksDashboardStudent.unit.js, src/components/organisms/HomeworksDashboardStudent.vue, src/components/organisms/HomeworksDashboardTeacher.vue, src/store/homeworks.js, src/store/homeworks.unit.js, stories/mockData/Homeworks.js
Fixes the course filter for students so they can select multiple courses. 
**Should be merged with BC-179, because of shared changes before merging into main**
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-195
=> BC 195 - fix multiple select courses for students

.github/workflows/clean.yml, CHANGELOG.md
Fix for mistake on branch delete event.
It's not GITHUB_REF what shoud be usedm but github.event.ref.
The actions are triggered on the main branch, so GITHUB_REF shows to main and github.event.ref has the branchname of the deleted branch.
https://docs.github.com/en/rest/reference/git#delete-a-reference
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3190
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2716
- https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/94
- https://github.com/hpi-schul-cloud/antivirus_check_service/pull/14
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/138
=> BC-589 - fix branch ref for delete event

CHANGELOG.md, ansible/group_vars/all/nuxt-client.yml, ansible/roles/nuxt-client/templates/deployment.yml.j2
=> BC-740 change ansible vars for docker image and tag

CHANGELOG.md, src/pages/rooms-overview.unit.js, src/pages/rooms-overview.vue
- Removing search filter while dragging
https://ticketsystem.hpi-schul-cloud.org/browse/BC-839
=> BC-839: Removing search filter while dragging

CHANGELOG.md, src/store/rooms.ts, src/store/rooms.unit.ts
- fetchAllElements action changed to generated API client
https://ticketsystem.hpi-schul-cloud.org/browse/BC-828
=> BC-828: changed fetchAllElements action to generated api client

CHANGELOG.md, src/components/organisms/administration/GeneralSettings.vue
https://ticketsystem.hpi-schul-cloud.org/browse/BC-878
=> BC-878 fix accidentialy deleting school logo

.github/workflows/test.yml, CHANGELOG.md
Set node version in test workflow
https://ticketsystem.hpi-schul-cloud.org/browse/BC-872
=> BC-872 - add set-up node action to test workflow

CHANGELOG.md, src/store/tasks.ts, src/store/tasks.unit.ts
BC-907 - Infinite number of requests in tasks.fetchAll
=> BC-907 - Infinite number of requests in tasks.fetchAll

src/components/atoms/vRoomAvatar.vue, src/pages/rooms-overview.unit.js, src/pages/rooms-overview.vue
- Implemented more spaces for course items on the rooms-overview page
- There will be always an extra row after the last element on the page
https://ticketsystem.hpi-schul-cloud.org/browse/BC-980
=> BC-980 - More empty spaces for courses on rooms-overview page

src/components/molecules/vTaskItemTeacher.unit.js, src/components/molecules/vTaskItemTeacher.vue
=> add show context menu button on hover

src/components/legacy/TheFooter.vue, src/themes/thr/components/legacy/TheFooter.vue
=> BC-1108 fixed thr support address

src/components/atoms/vRoomAvatar.vue, src/components/molecules/vRoomGroupAvatar.vue, src/themes/base/styles/variables/_spacing.scss
- Title of the course-avatar is adjusted based on user feedback
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1130
=> Feature/BC-1130 - Adjusting the title of the course-avatar component

package-lock.json, package.json
hpi-schul-cloud/schulcloud-server#3304
hpi-schul-cloud/schulcloud-client#2755
hpi-schul-cloud/dof_app_deploy#102
=> version 27.3.0

ansible/roles/nuxt-client-core/templates/configmap-files.yml.j2, http-headers.config.js
add frameSrc to the CSP Rules
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1282
hpi-schul-cloud/schulcloud-client#2766
=> BC-1282 - add frameSrc to the CSP Rules

src/themes/base/styles/index.scss, src/themes/default/styles/index.scss, src/themes/demo/styles/index.scss, src/themes/thr/styles/index.scss
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1275
=> BC-1275 - should adjust styles in themes to be consistent

ansible/roles/nuxt-client-core/templates/configmap-files.yml.j2
add nexboard to frame source for courses
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1334
hpi-schul-cloud/schulcloud-client#2772
=> BC-1334 - add nexboard to frame source for courses

locale/de.json, locale/en.json, locale/es.json, src/components/molecules/TaskItemMenu.unit.js, src/components/molecules/TaskItemMenu.vue, src/components/templates/TasksDashboardTeacher.vue
=> BC-557 - add copy action to task

src/components/molecules/RoomTaskCard.unit.ts, src/components/molecules/RoomTaskCard.vue
Added flag to show or hide the task description in rooms page.
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-1459
=> BC-1459 disable task description

.github/workflows/tag.yml, package-lock.json, package.json
=> 27.10.1 - Fix release Pipelines

locale/de.json, locale/en.json, locale/es.json
The modal to share a topic had a wrong text. This was changed for the languages german, english and spanish. In the ukrainian language the key wasn't used in the nuxt client and in the legacy client the wrong (sharing a course) text is used. Susi will take care of the ukrainian language changes.
- https://ticketsystem.dbildungscloud.de/browse/BC-1596
=> BC-1596 changed wording on lesson share modal

src/pages/administration/migration/index.unit.ts, src/store/import-users.ts
=> BC-1733 - fix store on ldap migration page

package-lock.json, package.json, src/themes/brb/components/legacy/TheFooter.vue
Fix the brb fooder
https://ticketsystem.dbildungscloud.de/browse/BC-1768
=> BC-1768 - Fixt the BRB fooder

package-lock.json, package.json, src/themes/brb/components/legacy/TheFooter.vue
The fix for the BRB fooder at 27.15.1 go to main
https://ticketsystem.dbildungscloud.de/browse/BC-1768
=> BC-1768 - Fix the BRB fooder (#2162)

package-lock.json
Separate PR for running `npm audit fix` to make it revertable.
=> BC-1662 Run npm audit fix

package-lock.json, package.json
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3465
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2864
https://github.com/hpi-schul-cloud/nuxt-client/pull/2166
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/259
=> version 27.17.0

.github/pull_request_template.md
Update PR template
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1783
hpi-schul-cloud/.github#1
hpi-schul-cloud/end-to-end-tests#416
hpi-schul-cloud/schulcloud-client#2870
hpi-schul-cloud/schulcloud-server#3475
=> BC-1783 - clean up public tech documentation

src/components/legacy/NavigationBar.unit.js, src/components/legacy/NavigationBar.vue, src/layouts/loggedoutFooter.vue
Opening imprint page while not logged in on federal states pages only shows dBildungcscloud logo. We also decided to display the navbar items and buttons just for the default theme on the imprint page.
https://ticketsystem.dbildungscloud.de/browse/BC-1818
=> BC-1818: Opening imprint page while not logged in shows wrong layout

src/components/molecules/TaskItemStudent.unit.js, src/components/molecules/TaskItemStudent.vue
As a student I see a wrong Icon on the task overview, when I submitted a task with a due date and the task is expired and when I submitted a task with a due date and due date is in the next 24 h. 
The remaining time chip should not be displayed when a student submitted a task.
https://ticketsystem.dbildungscloud.de/browse/BC-1862
=> BC-1862 -  Wrong Icons for students on task overview

package-lock.json, package.json
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/285
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3501
https://github.com/hpi-schul-cloud/nuxt-client/pull/2204
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2901
=> version 28.2.0

src/components/organisms/TasksList.vue, src/store/finished-tasks.ts
=> BC-1899 - loading finished tasks error

package-lock.json, package.json
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/288
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3508
https://github.com/hpi-schul-cloud/nuxt-client/pull/2212
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2908
=> version 28.3.0

src/components/organisms/ContentCard.vue, src/pages/administration/Migration.page.vue
When starting the nuxt client, there are eslint warnings that should be fixed.
https://ticketsystem.dbildungscloud.de/browse/BC-1996
=> BC-1996 - fix eslint warnings in nuxt

locale/de.json, locale/en.json, locale/es.json, locale/ua.json, src/components/molecules/RoomLessonCard.unit.ts, src/components/molecules/RoomLessonCard.vue, src/components/templates/RoomDashboard.unit.ts, src/components/templates/RoomDashboard.vue, src/serverApi/v3/api.ts, src/store/room.ts, src/store/types/env-config.ts
Initial implementation of copying lessons. Lessons are copied without content. 
https://ticketsystem.dbildungscloud.de/browse/BC-1555
related backend ticket:
https://ticketsystem.dbildungscloud.de/browse/BC-1928
related backend PR:
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3511
=> BC-1555 - lesson copy (frontend)

src/components/molecules/TaskItemMenu.vue, src/components/templates/TasksDashboardMain.unit.ts, src/components/templates/TasksDashboardMain.vue, src/components/templates/TasksDashboardStudent.unit.ts, src/components/templates/TasksDashboardStudent.vue, src/components/templates/TasksDashboardTeacher.unit.ts, src/components/templates/TasksDashboardTeacher.vue, src/store/tasks.ts, src/store/tasks.unit.ts
After closing the copy result modal the user will be redirected to the drafts tab, so that the user can immediately see the copied task.
https://ticketsystem.dbildungscloud.de/browse/BC-1864
=> BC-1864 - open draft tab after copying

ansible/roles/nuxt-client-core/templates/deployment.yml.j2, ansible/roles/nuxt-client-ldap/templates/deployment.yml.j2
=> BC-2084 decrease default nuxt memory limit

.github/workflows/push.yml, Dockerfile
=> BC-2078 get version from git during build

.github/workflows/tag.yml, Dockerfile
=> bc-2078 fetch-depth 0 during tag action

src/components/molecules/RoomLessonCard.vue, src/components/molecules/RoomTaskCard.vue
=> BC-2119 - Implement data-testid's for creation and deletion of tasks

src/components/organisms/DataTable/TableHeadRow.vue, src/pages/administration/StudentOverview.page.vue, src/pages/administration/student-overview.unit.js, src/store/env-config.ts, src/store/env-config.unit.ts, src/store/filePaths.unit.ts, src/store/types/env-config.ts
https://ticketsystem.dbildungscloud.de/browse/BC-2289
=> use consent feature flag

src/pages/administration/StudentOverview.page.vue, src/pages/administration/student-overview.unit.js
Remove bulk option "Analoge Einverständniserklärung" on student overview page (administration) if consent is not necessary
https://ticketsystem.dbildungscloud.de/browse/BC-2218
=> BC-2218 - adjust bulk options

src/plugins/store-accessor.ts
Teachers task overview page is empty. No tasks are loaded.
https://ticketsystem.dbildungscloud.de/browse/BC-2358
=> BC-2358 Tasks not loaded in task overview (only role teacher)

src/serverApi/v3/api.ts, src/store/copy.ts, src/store/copy.unit.ts
the breadcrumb url in copy result modal
should lead to the lessons/tasks in the new course,
for this the new courseId needs to be given
from backend in the API response, which we implement
BC-2369
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3610
=> BC-2369 - new copy course modal not copying correctly

src/pages/administration/StudentConsent.page.vue, src/themes/n21/components/templates/CommonTermsOfUse.vue
=> BC-2352 - use data privacy service instead of file

vue3_poc/build-plugins/proxy.ts, vue3_poc/package-lock.json, vue3_poc/package.json, vue3_poc/src/App.vue, vue3_poc/src/main.ts, vue3_poc/src/pages/TaskListPage.vue, vue3_poc/src/router/index.ts, vue3_poc/src/serverApi/v3/api.ts, vue3_poc/src/store/auth.ts, vue3_poc/vite.config.ts
=> BC 2407 - Vue 3 POC: Implement Authentication

src/serverApi/v3/api.ts, src/store/room.ts, src/store/room.unit.ts
=> BC-1513 Replace delete lesson v1 url with v3 url

vue3_poc/src/App.vue, vue3_poc/src/layouts/DefaultLayout.vue, vue3_poc/src/router/index.ts
=> BC-2331 - vue3 layouts

src/components/templates/impressum.vue
-Added newest member of the Dataport board to imprint page
https://ticketsystem.dbildungscloud.de/browse/BC-2486
=> BC-2486 - Add newest member of the Dataport board to imprint page

locale/de.json, locale/en.json, locale/es.json, locale/ua.json, src/pages/files/FilesOverview.page.vue, src/router/routes.js, src/serverMiddleware/routes.js, src/utils/sidebarBaseItems.js
This PR adds a new entry "Dateien" to the sidebar if the user has the permission to see it.
https://ticketsystem.dbildungscloud.de/browse/N21-400
https://ticketsystem.dbildungscloud.de/browse/N21-221
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2995
=> N21-400 Adds new page and sidebar entry for files

vue3_poc/package-lock.json, vue3_poc/package.json, vue3_poc/src/components/LanguageSelector.spec.ts, vue3_poc/src/components/LanguageSelector.vue, vue3_poc/src/layouts/DefaultLayout.vue, vue3_poc/src/locales/de.json, vue3_poc/src/locales/en.json, vue3_poc/src/main.ts, vue3_poc/src/pages/I18nPage.vue, vue3_poc/src/plugins/i18n.ts, vue3_poc/src/plugins/vuetify.ts, vue3_poc/src/router/index.ts, vue3_poc/src/store/types/Language.ts, vue3_poc/vite.config.ts
Vue 3 POC: Implement I18n
https://ticketsystem.dbildungscloud.de/browse/BC-2409
=> BC-2409 - vue3 i18n

package-lock.json
=> BC-2558-npm-audit-fix-prod

locale/de.json, locale/en.json, locale/es.json, locale/ua.json, src/components/share-course/ShareModal.unit.ts, src/components/share-course/ShareModal.vue, src/components/share-course/ShareModalOptionsForm.unit.ts, src/components/share-course/ShareModalOptionsForm.vue, src/store/share-course.ts, src/store/share-course.unit.ts
Now Sharing links for courses are valid for 21 instead of 7 days to avoid confusion about invalid links.
Wording "Zwischenspeicher" is changed to "Zwischenablage" (also modified wording for es and ua).
https://ticketsystem.dbildungscloud.de/browse/BC-2707
=> BC-2707 - Adapt duration for link validity and "Zwischenablage"

docs/4-Tools.md
=> fixed some spelling issues in the documentation

docs/CodeStyleguide.md
=> more spelling issues

src/components/atoms/vRoomAvatar.unit.ts, src/components/atoms/vRoomAvatar.vue, src/components/atoms/vRoomEmptyAvatar.vue, src/components/molecules/vRoomGroupAvatar.unit.ts, src/components/molecules/vRoomGroupAvatar.vue, src/components/share-course/ShareModalResult.vue, src/pages/RoomOverview.page.vue
layout changes in rooms overview
- space adjustment between course titel and archive date
- adjust width of searchbar and course avatar for mobile view
BC-2464
=> BC-2464 - Styling issues on course overview page

src/components/organisms/administration/GeneralSettings.vue, src/components/organisms/administration/PrivacySettings.vue
add testids for admin settings
BC-2882
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3048
* test id for rocket chat toggle
* test id for videoconference toggle
* test id for save settings
=> BC-2882 apply data-testid on the web elements related to Teams

.github/workflows/push.yml, .github/workflows/security-audit.yml, .github/workflows/tag.yml, .github/workflows/test.yml, .github/workflows/test_unstable_e2e.yml
=> BC-2889 limit github action permissions

.github/workflows/dependency-review.yml
=> BC-2937 let dependency-review-action check for vulnerbilities

.github/workflows/test.yml
https://ticketsystem.dbildungscloud.de/browse/BC-2867
=> BC-2867 Change workflow triggers

src/components/administration/AdminMigrationSection.vue
On the school settings page, the switch in the migration section looks like the switches in privacy settings (General Settings Section) now.
https://ticketsystem.dbildungscloud.de/browse/BC-2951
=> BC-2951 - Use correct switch in school settings

src/store/tasks.ts
refactor code back to working with valid backend limit so complete amount of tasks will be fetched
-> refactor of task module to be separated like finished tasks will be done in a follow up BC-3034
BC-2974
bug due to:
BC-2768
=> BC-2974 - Pagination limitation showing no tasks

package-lock.json, package.json, src/components/editor/CKEditor.unit.ts, src/components/editor/CKEditor.vue, src/pages/TaskCard.page.unit.ts
Update ckeditor and make math plugin available for editor in _regular_ mode
Add math rendering engine (KaTeX)
https://ticketsystem.dbildungscloud.de/browse/BC-2949
=> BC-2949 - math plugin

src/serverApi/v3/api.ts, src/store/task-card.ts, src/store/task-card.unit.ts
generate api
fix task-card store with the new types
BC-2806
=> BC-2806 - update types and api definition

server-proxy.js, src/router/server-route.js, webpack-config/dev-server-config.js
https://github.com/hpi-schul-cloud/nuxt-client/pull/2387
=> BC-3168 - The new file store is not available locally after removing nuxt

src/components/administration/external-tool/ExternalToolConfigParameter.vue, src/composables/external-tool-mappings.composable.ts, src/composables/external-tool-mappings.composable.unit.ts
This PR fixes the mapping of parameter entries. The default value was automatically set on save which was an mistake.
It also adds a test for that and activates immediately validation.
https://ticketsystem.dbildungscloud.de/browse/N21-241
=> N21-241 Fix schoolExternalTool parameter mapping

dockerconf/nginx.conf.template
=> BC-3275 - fix admin password change

dockerconf/nginx.conf.template, public/index.html, src/themes/base-vuetify.options.js
=> BC-3275 - Apply CSP to Vuetify theme

dockerconf/nginx.conf.template
Bug: Unable to use button "Received Consent on Paper".
Ticket [BC-3303](https://ticketsystem.dbildungscloud.de/browse/BC-3303)
=> BC-3303 - Fix admin consent on paper

dockerconf/nginx.conf.template
The school administration page is not reachable because of CSP issues.
Ticket [BC-3308](https://ticketsystem.dbildungscloud.de/browse/BC-3308)
=> BC-3308 - Fix Beta School Settings Page is not reachable

src/components/card-elements/AddCardElement.vue
Change dotted border to a simple line, so that it looks like the + Button at the bottom of a text-element (Review Feedback) 
BC-3307
=> BC-3307 - Change UI of "Add" button in TaskCard to line

.github/workflows/dependabot-to-jira.yml, .github/workflows/push.yml
=> BC-3143 adding dependabot to jira workflow

src/components/templates/TasksDashboardMain.vue
add dataTestId `fab_button_add_task` to create task button
BC-3675
BC-3693 (subtask)
=> BC-3675 - Add dataTestId for task create button

.github/workflows/dependabot-to-jira.yml, .github/workflows/dependency-review.yml
https://ticketsystem.dbildungscloud.de/browse/BC-3561
=> BC-3561 update pr title on dependabot pr

src/locales/de.json
=> BC-3692 - Fix task copy share typo

package-lock.json, package.json
https://ticketsystem.dbildungscloud.de/browse/BC-3721
=> BC-3721 - Dependency Updates

src/serverApi/v3/api.ts
Generate api 
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4069
=> N21-793 Generate Api

src/components/legacy/TheSidebar.vue
Improves styling of the sidebar  items
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-3925
Legacy: https://github.com/hpi-schul-cloud/schulcloud-client/pull/3176
=> BC-3925 - adjust styling sidebar items

src/components/date-time-picker/TimePicker.vue
Fix DateTimePicker component that throws an error while trying to generate a Date object out of faulty time value
https://ticketsystem.dbildungscloud.de/browse/BC-3935
=> BC-3935 - Fix DateTimePicker bug

src/utils/validationUtil.ts, src/utils/validationUtil.unit.ts
Adapts the officialSchoolNumber regex for query parameter of migration to prevent attacks.
https://ticketsystem.dbildungscloud.de/browse/N21-887
=> N21-887 adapts officialSchoolNumber regex for migration

src/serverApi/v3/api.ts
just to generate a new API-File to make sure types of the backend exist in this repo
BC-3691
=> BC-3691 - add course endpoint

src/components/feature-board/card/CardHost.vue, src/components/feature-board/shared/ElementTypeSelection.composable.ts, src/components/feature-board/shared/ElementTypeSelection.vue, src/components/feature-board/shared/FilePicker.composable.ts, src/components/feature-board/shared/FilePicker.vue
https://ticketsystem.dbildungscloud.de/browse/BC-3339
=> BC-3339 - refactor file element selection

.github/workflows/tag.yml, src/pages/administration/StudentCreate.page.vue
Fix bug in Safari on MacOS when input date is actually empty but form field shows current date.
This bug relates to the WebKit implemention for input type="date" used by Safari Browser:
https://developer.apple.com/forums/thread/728067
https://stackoverflow.com/questions/73866581/how-to-stop-safari-16-macos-defaulting-to-the-current-date-in-a-html-type-dat
Therefore eventhough the browser per default displays the current date, the fields' value is indeed **empty** and if the form is submitted the new student is saved **without birthdate**. 
https://ticketsystem.dbildungscloud.de/browse/BC-3979
=> BC-3979 - Safari date bug

src/serverApi/v3/api.ts
Generated Api
https://ticketsystem.dbildungscloud.de/browse/N21-535
Server PR: https://github.com/hpi-schul-cloud/schulcloud-server/pull/4102
=> N21-535 - generate api

package-lock.json, package.json, src/components/editor/CKEditor.unit.ts, src/components/editor/CKEditor.vue
Integrate and configure text background color setting in CK5
https://ticketsystem.dbildungscloud.de/browse/BC-4026
=> BC-4026 - Background colors in CK5

src/serverApi/v3/api.ts
BC-4104
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4161
=> BC-4104 - generate api

src/components/feature-board/shared/BoardApi.composable.ts, src/components/feature-board/shared/BoardApi.composable.unit.ts, src/components/feature-board/state/CardState.composable.ts, src/components/feature-board/state/CardState.composable.unit.ts, src/serverApi/v3/api.ts
Now Card skeletons are rendered with the same height as normal cards.
https://ticketsystem.dbildungscloud.de/browse/BC-4189
=> BC-4189 - CardHeight is not synced with the backend

src/layouts/legacyLoggedIn.vue
This reverts commit af4d3d8196447bb24509e95b9277f2dd467c4708.
Origin: https://github.com/hpi-schul-cloud/nuxt-client/pull/2570
- https://ticketsystem.dbildungscloud.de/browse/BC-4078
=> Revert "BC-4078-Fixing-the-dropdown-list-for-Win-Surface (#2570)"

ansible/group_vars/all/nuxt-client.yml
https://ticketsystem.dbildungscloud.de/browse/BC-4316
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/139
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4207
https://github.com/hpi-schul-cloud/version-aggregator/pull/8
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3217
https://github.com/hpi-schul-cloud/nuxt-client/pull/2599
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/214
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/37
=> BC-4316 pull images for ref and prod from quay.io

public/runtime.config.json, webpack-config/dev-server-config.js
Accessing the dev server on the development machine from another client on the local network leads to an infinite redirect loop.
[BC-4389](https://ticketsystem.dbildungscloud.de/browse/BC-4389)
=> BC-4389 - Infinite redirect

src/components/common/editor/CKEditor.vue
Add prefix for incomplete inserted URLs like "dataport.de"
https://ticketsystem.dbildungscloud.de/browse/BC-4387
=> BC-4387 - adjust editor config

src/components/feature-board/shared/BoardApi.composable.ts, src/components/feature-board/shared/BoardBreadcrumbs.composable.unit.ts
For students we cannot use the course API to get the course name (not authorized). We will use the room API instead.
[BC-4430](https://ticketsystem.dbildungscloud.de/browse/BC-4430)
=> BC-4430 - Get course name as a student unauthorized

package-lock.json, package.json
https://ticketsystem.dbildungscloud.de/browse/BC-4433
=> BC-4433 - Update @mdi/js

src/components/organisms/administration/GeneralSettings.vue
https://ticketsystem.dbildungscloud.de/browse/BC-4478
=> fix admin page general settings saving

src/pages/user-login-migration/UserLoginMigrationError.page.unit.ts, src/pages/user-login-migration/UserLoginMigrationError.page.vue
After sanatize html in BC4142 the error migration page was displayed wrong. This change will fix that.
https://ticketsystem.dbildungscloud.de/browse/N21-1073
=> N21-1073-fix-migration-error-page

src/themes/thr/components/templates/impressum.vue
Based on https://ticketsystem.dbildungscloud.de/browse/BC-4197, the text of the heading of the imprint of the TSC should be edited.
https://ticketsystem.dbildungscloud.de/browse/BC-4588
=> BC-4588 - Text adjustment of heading of the TSC imprint

src/pages/rooms/RoomDetails.page.vue
Fixes a bug on the room details page where the page title (title in the tab) would not show correctly.
https://ticketsystem.dbildungscloud.de/browse/BC-4524
=> BC-4524 - fix room details page title

src/components/feature-board/content-elements/FileContentElementMenu.vue
Too much space next to the icons in file edit three dot menu
BC-4632
- fix UI of file element 3 dot menu (spacing)
=> BC-4632 - Fix UI for file edit menu

src/pages/rooms/tools/RoomExternalToolsSection.unit.ts, src/pages/rooms/tools/RoomExternalToolsSection.vue
Fixes showing the dialog if an auto parameter for a ctl tool like official school number is missing.
https://ticketsystem.dbildungscloud.de/browse/N21-1119
=> N21-1119 Fix showing CTL dialog on missing auto param

.github/dependabot.yml
https://ticketsystem.dbildungscloud.de/browse/BC-4645
https://github.com/hpi-schul-cloud/nuxt-client/pull/2678
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3234
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4264
=> BC-4645 explicitely state that versioning:strategy is increase

src/components/feature-board/content-elements/RichTextContentElementEdit.vue, src/components/feature-board/shared/EditMode.composable.ts, src/components/feature-board/shared/InlineEditInteractionHandler.vue
=> BC-4631 - fixes ck5 overlay treated as outside click

src/store/context-external-tools.ts, src/store/context-external-tools.unit.ts, src/store/external-tools.ts, src/store/external-tools.unit.ts, src/store/school-external-tools.ts, src/store/school-external-tools.unit.ts
Fixes showing the outdated tool error dialog again
https://ticketsystem.dbildungscloud.de/browse/N21-1129
=> N21-1129 fix error dialog for ctl

src/components/feature-board/board/BoardColumnHeader.vue, src/components/feature-board/card/CardHost.unit.ts, src/components/feature-board/card/CardHost.vue, src/components/feature-board/card/CardTitle.vue, src/components/feature-board/shared/BoardAnyTitleInput.vue, src/components/feature-board/shared/ElementTypeSelection.vue
Fixes the expected behavior of regaining focus after a column was moved via keyboard
- https://ticketsystem.dbildungscloud.de/browse/BC-4719
=> BC-4719 - fixes focus loss on keyboard move

src/pages/rooms/RoomDetails.page.vue, src/pages/tasks/TaskOverview.page.vue, src/pages/tasks/TaskOverview.unit.ts
https://ticketsystem.dbildungscloud.de/browse/BC-4734
Also adjust page title on task overview to show the instance name as well, as we do on all other pages
=> BC-4734 - Fix Page Title on Room Detail Page

src/components/molecules/RoomLessonCard.vue
Removes indentation of topic in the room lesson card.
https://ticketsystem.dbildungscloud.de/browse/BC-4796
=> BC-4796 - RoomLessonCard: remove indentation of "topic"

src/serverApi/v3/api.ts
https://ticketsystem.dbildungscloud.de/browse/N21-908
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4304
=> N21-908 Generate API

package-lock.json, package.json
Includes Updates for
- @vueuse/core (https://ticketsystem.dbildungscloud.de/browse/BC-4714)
- @types/vuelidate (https://ticketsystem.dbildungscloud.de/browse/BC-4715)
- @golevelup/ts-jest (https://ticketsystem.dbildungscloud.de/browse/BC-4716)
- @vue/eslint-config-typescript (https://ticketsystem.dbildungscloud.de/browse/BC-4717)
=> BC-4714 - Dependency Updates

src/serverApi/v3/api.ts
https://ticketsystem.dbildungscloud.de/browse/N21-909
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4314
=> N21-909 Generate API

src/serverApi/v3/api.ts
Generates api for ctl tool logos
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4312
https://ticketsystem.dbildungscloud.de/browse/N21-1117
=> N21-1117 api generation

src/serverApi/v3/api.ts
https://ticketsystem.dbildungscloud.de/browse/N21-839
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4323
=> N21-839 Generate API

.github/pull_request_template.md
To make sure the accessability is kept in mind, the PRs for FE should include a reminder checkbox for that topic.
BC-4870
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3271
=> BC-4870 - Add a11y reminder checkbox into FE PR templates

src/components/legacy/TheFooter.unit.js, src/components/legacy/TheFooter.vue, src/layouts/loggedOut.layout.vue, src/themes/brb/alias.config.js, src/themes/brb/components/legacy/TheFooter.vue, src/themes/n21/alias.config.js, src/themes/n21/components/legacy/TheFooter.vue, src/themes/thr/alias.config.js, src/themes/thr/components/legacy/TheFooter.vue
All nuxt/vue pages show only default footer instead of theme specific one.
BC-4854
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3275
- fix typo in theming replacements
=> BC-4854 - Wrong footer on nuxt-pages

src/pages/user-login-migration/UserLoginMigrationSuccess.page.unit.ts, src/pages/user-login-migration/UserLoginMigrationSuccess.page.vue
Fixes displaying the description for a successfull migration again
https://ticketsystem.dbildungscloud.de/browse/N21-1205
=> N21-1205 fix showing description again

src/components/icons/material/index.ts, src/components/molecules/TaskItemMenu.vue
=> BC-4941 - fix a couple of icons

src/serverApi/v3/api.ts
The updatedAt value was added to the account response in the Schulcloud Server to display it in the Superhero Dashboard.
https://ticketsystem.dbildungscloud.de/browse/EW-547
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4357
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/227
=> EW-547 Showing updatedAt information in the SHD

src/components/feature-board-file-element/content/footer/ContentElementFooter.unit.ts, src/components/feature-board-file-element/content/footer/ContentElementFooter.vue, src/components/feature-board-file-element/content/footer/attributes/FileAttributes.unit.ts, src/components/feature-board-file-element/content/footer/attributes/FileAttributes.vue
=> BC-5417 - Replace chips with text

src/components/feature-board-submission-element/components/SubmissionItemsTeacherDisplay.vue
- removes elevation from submission element
- removes multi sort from submission list/table
- decreases sorting icon size to have a one line table header
https://ticketsystem.dbildungscloud.de/browse/BC-5443
=> BC - 5443 - remove sub el shadow

src/components/feature-board-submission-element/components/SubmissionContentElementDisplay.vue, src/components/feature-date-time-picker/DatePicker.vue
https://ticketsystem.dbildungscloud.de/browse/BC-5451
=> BC-5451 - remove date format localisation

src/components/rooms/RoomExternalToolCard.unit.ts, src/components/rooms/RoomExternalToolCard.vue, src/pages/rooms/tools/RoomExternalToolsSection.vue, src/store/external-tool/index.ts, src/store/external-tool/mapper/common-tool.mapper.ts, src/store/external-tool/mapper/external-tool.mapper.ts, src/store/external-tool/tool-launch-request-method.enum.ts, src/store/external-tool/tool-launch-request.ts, src/store/external-tools.unit.ts, tests/test-utils/factory/index.ts, tests/test-utils/factory/toolLaunchRequestFactory.ts, tests/test-utils/factory/toolLaunchRequestResponseFactory.ts
Moves loading launch request to room external tool card itself to prevent popup blocking because of firefox and safaris security feature.
https://ticketsystem.dbildungscloud.de/browse/N21-1190
=> N21-1190 move loading launch data to card

src/components/rooms/RoomExternalToolCard.unit.ts, src/components/rooms/RoomExternalToolCard.vue, src/pages/rooms/tools/RoomExternalToolsSection.unit.ts, src/pages/rooms/tools/RoomExternalToolsSection.vue, src/store/external-tools.ts, src/store/external-tools.unit.ts
Adjusts error handling for ctl tool card. 
https://ticketsystem.dbildungscloud.de/browse/N21-1341
=> N21-1341 adjusted error handling in for tool card

.github/workflows/test.yml
https://ticketsystem.dbildungscloud.de/browse/BC-5106
=> BC-5106 update sonarcloud and specificy java version

src/components/feature-board-file-element/content/display/video-display/VideoDisplay.unit.ts, src/components/feature-board-file-element/content/display/video-display/VideoDisplay.vue
=> BC-5652 - Remove download option from video player menu

src/components/feature-board-file-element/FileContentElement.unit.ts, src/components/feature-date-time-picker/TimePicker.unit.ts, src/components/feature-date-time-picker/TimePicker.vue
Bug description: 
- select time inside submission via keyboard 
-- navigate inside time-select with arrow down > no scrolling/focus
-- navigate inside time-select with arrow up > moves card element
BC-5523
- card element movement blocked when in time select with keyboard
- currently selected/highlighted time with keyboard will scroll into view for user
=> BC-5523 - Fix time select in submission-element

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/locales/uk.json
=> BC-5635 - Change translation for alternative text hint

src/components/feature-board-file-element/content/display/audio-display/AudioDisplay.vue, src/components/feature-board-file-element/content/display/video-display/VideoDisplay.vue, src/components/feature-board-file-element/content/inputs/caption/CaptionText.vue
=> BC-5634 - Style file element

src/components/rooms/RoomVideoConferenceCard.vue
https://ticketsystem.dbildungscloud.de/browse/N21-1455
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3344
=> N21-1455 Fix BBB pulsating dot in reduced animation mode

src/components/feature-board-external-tool-element/ExternalToolElement.unit.ts, src/components/feature-board-external-tool-element/ExternalToolElement.vue
Adds immediate opening of configuration dialog of ctl tool elements on board
https://ticketsystem.dbildungscloud.de/browse/N21-1418
=> N21-1418 open ctl dialog on board immediately

ansible/roles/nuxt-client-core/templates/deployment.yml.j2
To Improve the distribution of PODs to the least number of kubernetes worker nodes who is Required 
but also to secure that the PODs of one Deployment are distributed over the Fault Zones and Node pools
the pod affinity and anti affinity are set.
**Affernety number calculation:** 
**_Assign Number for an host_** = 0 - 20 X _Fault Zone_  - 10 X _Node Pool_ + 9 X _Host_ 
**_Host_**  = 1 if on the host runs an POD from the Schulcloud-Verbund on any namespace
**_Host_**  = 0 if on the host runs no POD from the Schulcloud-Verbund on any namespace
**_Node Pool_** = 1 if on a host of this node pool runs an POD from the Deployment
**_Node Pool_** = 0 if on no host of this node pool runs an POD from the Deployment
**_Fault Pool_** = 1 if on a host of this fault zone runs an POD from the Deployment …
=> BC-5423 - Add POD affinity and anti-affinity

src/components/feature-board-drawing-element/DrawingContentElement.vue, src/components/feature-board-external-tool-element/ExternalToolElementMenu.vue, src/components/feature-board-file-element/FileContentElement.vue, src/components/feature-board-link-element/components/LinkContentElement.vue, src/components/feature-board-submission-element/components/SubmissionContentElement.vue, src/components/feature-board/board/BoardColumnHeader.vue, src/components/feature-board/card/CardHost.vue, src/components/ui-board/BoardMenu.vue, src/components/ui-board/BoardMenuActionDelete.vue, src/components/ui-board/BoardMenuEvent.enum.ts, src/components/ui-board/index.ts, src/components/ui-board/injection-tokens.ts
After vue3 upgrade the deletion of elements, cards and columns on the board doesn't work as expected.
BC-5938
BC-5948
BC-5949
=> BC-5938 - fix delete element, card, column (board)

src/components/organisms/administration/AuthSystems.unit.js, src/components/organisms/administration/AuthSystems.vue
fixes brolen build link in AuthSystems.vue
https://ticketsystem.dbildungscloud.de/browse/N21-1601
=> N21-1602 fix link

src/components/administration/AdminMigrationSection.vue, src/components/organisms/Ldap/LdapClassesSection.vue, src/components/organisms/administration/PrivacySettings.vue, src/components/share/ShareModalOptionsForm.vue, src/components/templates/TasksDashboardMain.vue, src/pages/rooms/RoomOverview.page.vue, src/pages/rooms/tools/RoomVideoConferenceSection.vue, src/plugins/vuetify.ts
Vuetify 3 allows us to set default prop values globally. This PR defines the v-switch  props we want to have as default .
Jira: BC-5887
* add default props in vuetify.ts
`VSwitch: { inset: true, flat: true, color: "primary" }`
=> BC-5887 - Vue3 upgrade: v-switch

src/pages/administration/ClassOverview.page.unit.ts, src/pages/administration/ClassOverview.page.vue, src/serverApi/v3/api.ts, src/store/group.ts, src/store/group.unit.ts
generate api + add the new 'calledFrom' property to the getClasses request in new classOverview page
https://ticketsystem.dbildungscloud.de/browse/N21-1623
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3377
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4659
=> N21-1623 fix class visibility

src/components/external-tools/configuration/external-tool-validation.composable.unit.ts, src/serverApi/v3/api.ts, src/store/context-external-tools.unit.ts, src/store/external-tool/mapper/external-tool.mapper.ts, src/store/external-tool/tool-parameter.ts, src/store/school-external-tools.unit.ts, tests/test-utils/factory/customParameterResponseFactory.ts, tests/test-utils/factory/toolParameterFactory.ts
generate api for isProtected attribute of customParameter of external tools
https://ticketsystem.dbildungscloud.de/browse/N21-1587
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/241
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4658
=> N21-1587 generate api and adjust tests

src/pages/administration/ClassOverview.page.unit.ts, src/pages/administration/ClassOverview.page.vue
In Class overview page a pagetitle is added for a11y and a locale replaces a hardcoded value.
https://ticketsystem.dbildungscloud.de/browse/N21-1596
=> N21-1596 add locale and pagetitle

src/components/feature-board/board/Board.vue
Remove device detection output of current drag-start-delay.
https://ticketsystem.dbildungscloud.de/browse/BC-5130
=> BC-5130 - device detection cleanup

src/components/base/BaseDialog/BaseDialog.unit.js, src/components/base/BaseInput/BaseInput.unit.js, src/components/base/BaseInput/BaseInputCheckbox.unit.js, src/components/base/BaseInput/BaseInputDefault.unit.js, src/components/base/BaseInput/BaseInputHidden.unit.js, src/components/base/BaseInput/BaseInputRadio.unit.js, src/components/base/BaseModal.unit.js, src/components/organisms/FormCreateUser.unit.js, tests/test-utils/setup/createTestingVuetify.ts
Vue3 upgrade: refactor src/components/base tests
BC-6081
=> BC-6081 - Vue3 upgrade: refactor src/components/base tests

src/store/auth.unit.ts, src/store/news.unit.ts
BC-6084 - Vue3 upgrade: refactor src/store tests
BC-6084
=> BC-6084 - Vue3 upgrade: refactor src/store tests

src/router/guards/multi.guard.unit.ts, src/router/guards/permission.guard.unit.ts, src/router/guards/validate-query-parameters.guard.unit.ts
Vue3 upgrade: refactor src/router tests
BC-6083
=> BC-6083 - Vue3 upgrade: refactor src/router tests

src/plugins/i18n.unit.js
Vue3 upgrade: refactor src/plugins tests
BC-6140
=> BC-6140: Vue3 upgrade: refactor src/plugins tests

src/utils/api.unit.ts, src/utils/ldapConstants.js, tests/test-utils/mountComposable.ts
Vue3 upgrade: refactor src/utils tests
BC-6146
=> BC-6146 - Vue3 upgrade: refactor src/utils tests

src/components/data-board/BoardPageInformation.composable.unit.ts, src/components/data-board/BoardState.composable.unit.ts, src/components/data-board/CardState.composable.unit.ts, src/components/data-board/ContentElementState.unit.ts, src/components/data-external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts, src/components/data-provisioning-options/ProvisioningOptionsApi.composable.unit.ts, src/components/data-provisioning-options/ProvisioningOptionsState.composable.unit.ts, src/components/error-handling/ErrorHandler.composable.unit.ts, src/components/feature-board-file-element/shared/composables/FileStorageNotifications.composable.unit.ts, src/components/feature-board-link-element/composables/MetaTagExtractorApi.composable.unit.ts, src/components/feature-board-submission-element/composables/SubmissionContentElementState.composable.unit.ts, src/components/ui-confirmation-dialog/Confirmation.composable.unit.ts, src/components/ui-confirmation-dialog/DeleteConfirmation.composable.unit.ts, src/components/ui-light-box/LightBox.composable.unit.ts, src/components/util-board/BoardNotifier.composable.unit.ts, src/composables/copy.unit.ts, src/composables/loadingState.unit.ts, src/utils/inject/inject-strict.unit.ts, tests/test-utils/mountComposable.ts
Vue3 upgrade: refactor src/composables tests
BC-6080
=> BC-6080 - Vue3 upgrade: refactor src/composables tests

src/components/administration/AdminMigrationSection.vue, src/components/external-tools/configuration/ExternalToolConfigurator.vue, src/components/molecules/Alert.vue, src/components/molecules/ImportModal.vue, src/components/organisms/administration/ImportUsers.vue, src/components/organisms/administration/SchoolPolicy.vue, src/components/organisms/administration/SchoolPolicyFormDialog.vue, src/components/organisms/administration/SchoolTerms.vue, src/components/organisms/administration/SchoolTermsFormDialog.vue, src/components/page-class-members/ClassMembersInfoBox.vue, src/components/rooms/RoomVideoConferenceCard.vue, src/components/ui-alert/BaseAlert.vue, src/pages/administration/SchoolSettings.page.vue, src/pages/rooms/tools/RoomExternalToolsOverview.vue, src/plugins/vuetify.ts
Adds default props for v-alert in vuetify.ts. 
BC-5887
- adds `VAlert: { variant: "tonal" }` in vuetify.ts  as default and removes the prop from the components
- fix transition
- removes prominent prop
=> BC-5887 - Vuetify 3 v-alert

src/components/external-tools/configuration/ExternalToolConfigParameter.vue, src/components/external-tools/configuration/ExternalToolConfigurator.vue, src/components/feature-board-external-tool-element/ExternalToolElementConfigurationDialog.vue, src/components/molecules/AddContentModal.vue, src/components/molecules/ImportModal.vue, src/components/molecules/RoomModal.vue, src/components/molecules/vImportUsersMatchSearch.vue, src/components/organisms/FormCreateUser.vue, src/components/organisms/Pagination.vue, src/components/organisms/administration/AuthSystems.vue, src/components/organisms/administration/GeneralSettings.vue, src/components/organisms/administration/ImportUsers.vue, src/components/organisms/administration/SchoolPolicyFormDialog.vue, src/components/organisms/administration/SchoolTermsFormDialog.vue, src/components/share/ImportModal.vue, src/components/share/SelectCourseModal.vue, src/components/share/ShareModalResult.vue, src/components/templates/TasksDashboardMain.vue, src/components/ui-date-time-picker/DatePicker.vue, src/components/ui-date-time-picker/TimePicker.vue, src/pages/LernStoreOverview.page.vue, src/pages/administration/StudentCreate.page.vue, src/pages/context-external-tool/ContextExternalToolConfigurator.page.vue, src/pages/rooms/RoomDetails.page.vue, src/pages/rooms/RoomList.page.vue, src/pages/rooms/RoomOverview.page.vue, src/plugins/vuetify.ts
Add defaults for vuetify inputs in vuetify.ts
BC-5887
define defaults in vuetify.ts
- `VAutocomplete: { color: "primary" },`
- `VFileInput: { variant: "underlined", color: "primary" },`
- `VSelect: { variant: "underlined", color: "primary" },`
- `VTextField: { variant: "underlined", color: "primary" }`
=> BC-5887 - Vue3 upgrade:  vuetify inputs

src/components/feature-board-link-element/components/LinkContentElement.vue, src/components/feature-board-link-element/components/LinkContentElementCreate.unit.ts, src/components/feature-board-link-element/components/LinkContentElementCreate.vue, src/components/feature-board-link-element/components/LinkContentElementDisplay.unit.ts, src/components/feature-board-link-element/components/LinkContentElementDisplay.vue, src/components/ui-board/BoardMenu.vue
Fixing the link element to work with vue3 and vuetify3.
BC-5939
=> BC-5939 - fix link element

src/locales/de.json, src/locales/en.json, src/locales/es.json, src/locales/uk.json
This PR will change the naming of the label for deactivation of ctl tool in school external tool configuration.
=> N21-1650 Ctl deactivation label

src/components/copy-result-modal/CopyResultModal.unit.ts, src/components/copy-result-modal/CopyResultModalList.unit.ts, src/components/copy-result-modal/CopyResultModalListItem.unit.ts
Because of the vue3 upgrade we need to refactor the following tests (src/components/copy-result-modal):
copy-result-modal/CopyResultModal.unit.ts
copy-result-modal/CopyResultModalListItem.unit.ts
copy-result-modal/CopyResultModalList.unit.ts
BC-6163
=> BC-6163 - Vue3 upgrade: refactor src/components/copy-result-modal tests

src/components/share/ShareModalOptionsForm.vue, src/pages/rooms/tools/RoomVideoConferenceSection.vue, src/plugins/vuetify.ts
Replaces the v-swtiches with v-checkboxes in the share modal and room video conference section
BC-5887
-  add `VCheckbox: { color: "primary" }` in vuetify.ts
- replace v-switches with v-checkboxes in ShareModalOptionsForm.vue and RoomVideoConferenceSection.vue
=> BC-5887 vuetify checkboxes

src/mixins/infiniteScrolling.js, src/mixins/infiniteScrolling.unit.js, src/mixins/toastsFromQueryString.unit.js
Because of the vue3 upgrade we need to refactor the following tests (src/mixins):
userIsTabbing.unit.js
toastsFromQueryString.unit.js
print.unit.js
infiniteScrolling.unit.js
contentMeta.unit.js
controllableData.unit.js
BC-6160
=> BC-6160 - Vue3 upgrade: refactor src/mixins tests

src/components/ui-board/BoardMenu.unit.ts, src/components/ui-board/BoardMenuAction.unit.ts, src/components/ui-board/BoardMenuActionDelete.unit.ts, src/components/ui-board/BoardMenuActionMoveDown.unit.ts, src/components/ui-board/BoardMenuActionMoveLeft.unit.ts, src/components/ui-board/BoardMenuActionMoveRight.unit.ts, src/components/ui-board/BoardMenuActionMoveUp.unit.ts, src/components/ui-board/LineClamp.unit.ts, src/components/ui-board/content-element/ContentElementBar.unit.ts, src/components/ui-board/content-element/ContentElementDisplay.unit.ts, src/components/ui-board/content-element/ContentElementTitleIcon.unit.ts
Fixing all **tests** of module **ui-board**
BC-6190
=> BC-3844 - fix ui board tests

src/components/share/ImportFlow.unit.ts, src/components/share/ImportModal.unit.ts, src/components/share/SelectCourseModal.unit.ts, src/components/share/SelectCourseModal.vue, src/components/share/ShareModal.unit.ts, src/components/share/ShareModalOptionsForm.unit.ts, src/components/share/ShareModalOptionsForm.vue, src/components/share/ShareModalResult.unit.ts
Fixes components/share tests. Also fixes a bug in the SelectCourseModal.vue, which lead to an error when importing tasks or lessons.
BC-6187
=> BC-6187 - Vue3 upgrade: fix components/share tests

src/components/feature-board-file-element/FileContentElement.unit.ts, src/components/feature-board-file-element/content/FileContent.unit.ts, src/components/feature-board-file-element/content/inputs/FileInputs.unit.ts, src/components/feature-board-file-element/content/inputs/alternative-text/AlternativeText.unit.ts, src/components/feature-board-file-element/content/inputs/caption/CaptionText.unit.ts, src/components/feature-board-file-element/content/inputs/caption/CaptionText.vue, src/components/feature-board-file-element/shared/composables/FileStorageApi.composable.unit.ts, src/components/feature-board-file-element/shared/composables/FileStorageNotifications.composable.unit.ts, src/components/feature-board-file-element/upload/FileUpload.unit.ts, src/components/feature-board-file-element/upload/file-picker/FilePicker.unit.ts
=> BC-6249 fix file-element tests

src/components/feature-board-file-element/content/alert/FileAlerts.unit.ts, src/components/feature-board-file-element/content/display/FileDisplay.unit.ts, src/components/feature-board-file-element/content/display/audio-display/AudioDisplay.unit.ts, src/components/feature-board-file-element/content/display/audio-display/SpeedMenu.unit.ts, src/components/feature-board-file-element/content/display/file-description/FileDescription.unit.ts, src/components/feature-board-file-element/content/display/image-display/ImageDisplay.unit.ts, src/components/feature-board-file-element/content/display/pdf-display/PdfDisplay.unit.ts, src/components/feature-board-file-element/content/display/video-display/VideoDisplay.unit.ts, src/components/feature-board-file-element/content/footer/ContentElementFooter.unit.ts, src/components/feature-board-file-element/content/footer/attributes/FileAttributes.unit.ts, src/components/feature-board-file-element/content/footer/download/FileDownload.unit.ts
=> BC-6172 - Refactor file element tests part 1

src/components/base/BaseDialog/BaseDialog.vue, src/components/base/BaseModal.vue, src/components/lern-store/AddContentModal.vue, src/components/lern-store/NotificationModal.vue, src/components/molecules/InfoModalFullWidth.vue, src/components/molecules/ModalBodyInfo.vue, src/components/molecules/ModalFooter.vue, src/components/organisms/AutoLogoutWarning.vue
https://ticketsystem.dbildungscloud.de/browse/BC-6289
=> BC-6289 - vue3 lernstore modal

src/components/feature-render-html/RenderHTML.unit.ts
fix components/feature-render-html tests
BC-6177
=> BC-6177 - fix components/feature-render-html tests

src/components/feature-board-file-element/content/inputs/FileInputs.vue, src/components/feature-board-file-element/content/inputs/alternative-text/AlternativeText.vue, src/components/feature-board-file-element/content/inputs/caption/CaptionText.vue
https://ticketsystem.dbildungscloud.de/browse/BC-6324
=> BC-6324- Fix styling of file element inputs

src/components/util-input-masks/InputMask.unit.ts
util-input-masks/InputMask.unit.ts
BC-6196
=> BC-6196 - Vue3 upgrade: fix components/util-input-masks tests

src/components/data-provisioning-options/ProvisioningOptionsState.composable.unit.ts
data-provisioning-options/ProvisioningOptionsState.composable.unit.ts
data-provisioning-options/ProvisioningOptionsApi.composable.unit.ts
BC-6166
=> BC-6166 - Vue3 upgrade: fix src/components/data-provisioning-options tests

src/components/lern-store/LernstoreDetailView.vue, src/components/molecules/ContentSearchbar.vue, src/components/organisms/ContentCard.vue
=> BC-6076 - add test ids

src/components/ui-date-time-picker/DatePicker.unit.ts, src/components/ui-date-time-picker/DateTimePicker.unit.ts, src/components/ui-date-time-picker/TimePicker.unit.ts
https://ticketsystem.dbildungscloud.de/browse/BC-6192
=> BC-6192 - fix date time picker tests

src/components/organisms/administration/PrivacySettings.vue
additional data-testids in the new school administration page for these toggles 
1. Activate student visibility - data-testid="admin-school-toggle-student-visibility"
2. Learning Store for students - data-testid="admin-school-toggle-learning-store"
https://ticketsystem.dbildungscloud.de/browse/BC-6354
=> BC-6354 added data-testids

src/components/feature-board-submission-element/components/SubmissionContentElement.unit.ts, src/components/feature-board-submission-element/components/SubmissionContentElementDisplay.unit.ts, src/components/feature-board-submission-element/components/SubmissionContentElementEdit.unit.ts, src/components/feature-board-submission-element/components/SubmissionContentElementTitle.unit.ts, src/components/feature-board-submission-element/components/SubmissionItemStudentDisplay.unit.ts, src/components/feature-board-submission-element/components/SubmissionItemsTeacherDisplay.unit.ts, src/components/feature-board-submission-element/composables/SubmissionContentElementState.composable.unit.ts
Vue3 upgrade: fix components/feature-board-submission-element tests
BC-6174
=> BC-6174: fix components/feature-board-submission-element tests

src/components/external-tools/configuration/ExternalToolConfigParameter.unit.ts, src/components/external-tools/configuration/ExternalToolConfigParameter.vue, src/components/external-tools/configuration/ExternalToolConfigSettings.unit.ts, src/components/external-tools/configuration/ExternalToolConfigurator.unit.ts, src/components/external-tools/configuration/ExternalToolConfigurator.vue, src/components/external-tools/configuration/ExternalToolSelectionRow.unit.ts, src/components/external-tools/configuration/ExternalToolSelectionRow.vue, src/components/external-tools/configuration/external-tool-validation.composable.unit.ts
Vue3 upgrade: fix src/components/external-tools tests
BC-6168
=> BC-6168 - fix src/components/external-tools tests

src/components/lern-store/LernStoreGrid.unit.ts, src/components/lern-store/LernStorePlayer.unit.js, src/components/lern-store/LernstoreCollectionDetailView.unit.js, src/components/lern-store/LernstoreDetailView.unit.js
lern-store/LernStoreGrid.unit.ts
lern-store/LernstoreCollectionDetailView.unit.js
lern-store/LernstoreDetailView.unit.js
lern-store/LernStorePlayer.unit.js
BC-6180
=> BC-6180 - Vue3 upgrade: fix components/lern-store tests

jest.config.js, src/components/h5p/H5PEditor.unit.ts, src/components/h5p/H5PPlayer.unit.ts
Vue3 upgrade: fix components/h5p tests
BC-6178
=> BC-6178: fix components/h5p tests

src/components/feature-board-external-tool-element/ExternalToolElement.vue, src/components/rooms/RoomBaseCard.unit.ts, src/components/rooms/RoomBaseCard.vue, src/components/rooms/RoomCardChip.unit.ts, src/components/rooms/RoomCardChip.vue, src/components/rooms/RoomExternalToolCard.unit.ts, src/components/rooms/RoomVideoConferenceCard.unit.ts
Fixes components/rooms tests
BC-6186
- remove cover from v-img in RoomBaseCard and ExternalToolElement, because there was a wrong eslint vuetify warning, default is contain now
- remove hover  false because vuetify bug is fixed now
=> BC-6186 - Vue3 upgrade: fix components/rooms tests

src/components/copy-result-modal/CopyResultModal.unit.ts, src/components/page-class-members/ClassMembers.page.unit.ts, src/components/page-class-members/ClassMembers.page.vue, src/components/page-class-members/ClassMembersInfoBox.unit.ts, src/components/page-class-members/ClassMembersInfoBox.vue
page-class-members/ClassMembersInfoBox.unit.ts
page-class-members/ClassMembers.page.unit.ts
BC-6184
=> BC-6184 - Vue3 upgrade: fix components/page-class-members tests

src/components/templates/DefaultWireframe.unit.js, src/components/templates/RoomDashboard.unit.ts, src/components/templates/RoomWrapper.unit.ts, src/components/templates/TasksDashboardMain.unit.ts, src/components/templates/TasksDashboardStudent.unit.ts, src/components/templates/TasksDashboardTeacher.unit.ts
Vue3 upgrade: fix components/templates tests
BC-6188
=> BC-6188: fix components/templates tests

src/components/util-validators/validators.unit.ts
Vue3 upgrade: fix components/util-validators tests
BC-6197
=> BC-6197: fix components/util-validators tests

src/components/ui-light-box/LightBox.composable.unit.ts
Vue3 upgrade: fix src/components/ui-ligh-box tests
BC-6443
=> BC-6443 - Vue3 upgrade: fix src/components/ui-ligh-box tests

src/components/data-group/GroupState.composable.unit.ts
Vue3 upgrade: src/components/data-group tests
BC-6442
=> BC-6442 - fix src/components/data-group tests

src/components/atoms/vCustomBreadcrumbs.vue, src/components/templates/TasksDashboardMain.vue, src/pages/rooms/RoomDetails.page.vue, src/styles/global.scss, src/styles/utility/_links.scss
The link color is now the primary color.
BC-6416
-  use primary color for links
- add secondary color for legacy tabs in room details page
- remove previously added classes for breadcrumbs
- consistent styling tabs room details page and task overview
=> BC-6416 - fix color links

src/components/external-tools/configuration/ExternalToolSelectionRow.unit.ts, src/components/external-tools/configuration/ExternalToolSelectionRow.vue
v-img needs width attribute now to have a placeholder which will be replaced after loading the image from src.
- https://ticketsystem.dbildungscloud.de/browse/N21-1715
- https://ticketsystem.dbildungscloud.de/browse/BC-6349
=> BC-6349 N21-1715 fix tool autocomplete

src/components/feature-board/board/BoardColumnGhostHeader.vue
- https://ticketsystem.dbildungscloud.de/browse/BC-6391
- https://docs.dbildungscloud.de/pages/viewpage.action?pageId=310445271
=> BC-6391 - Fixing GhostColumnHeader Layout Issue in Bug Hunt Table #4

src/components/feature-editor/CKEditor.vue
Unordered and ordered lists have styling issues due to implicit padding settings in ck editor usage (board and news).
BC-6526
=> BC-6526 - Vue3 upgrade: Fix list padding

src/serverApi/v3/api.ts
https://ticketsystem.dbildungscloud.de/browse/BC-4663
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4737
=> BC-4663 Update api client with me route

src/serverApi/v3/api.ts
BC-6365
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4731
=> BC-6365 - update api definition

src/pages/NewsCreate.page.vue, src/pages/NewsEdit.page.vue, src/router/routes.ts
=> BC-6523 - news cancel error

ansible/roles/nuxt-client-core/templates/deployment.yml.j2
=> BC-6303 reduce startupProbe failureThreshold

src/locales/en.json, src/locales/es.json, src/locales/uk.json
fix the language-keys in the different language files
BC-6529
=> BC-6529 - broken language in delete dialogs

src/components/molecules/SkipLinks.vue, src/layouts/lernStore.layout.vue, src/layouts/loggedIn.layout.vue, src/layouts/loggedOut.layout.vue
Bug Hunt A58: Jump to main content not working
BC-6554
=> BC-6554 - Fix jump to main content

src/components/external-tools/configuration/ExternalToolConfigParameter.unit.ts, src/components/external-tools/configuration/ExternalToolConfigParameter.vue, src/components/external-tools/configuration/ExternalToolConfigSettings.vue
Fixes external tools configuration with using script setup which implicit uses modelValue (https://v3-migration.vuejs.org/breaking-changes/v-model.html)
- https://ticketsystem.dbildungscloud.de/browse/BC-6557
=> BC-3844 BC-6557 fix external tools

src/serverApi/v3/api.ts, src/store/content.ts, src/store/content.unit.ts, src/store/room.ts
BC-5342
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4760
=> BC-5342 - change get lessons to v3

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/plugins/i18n.ts, src/vue-i18n.d.ts, tests/test-utils/setup/createTestingI18n.ts, vue.config.js, webpack-config/vue-i18n-loader.js
Vue3 upgrade: fix CSP integration after i18n changes
BC-6612
=> BC-6612: fix CSP integration after i18n changes

src/pages/administration/student-consent.unit.js, src/store/filePaths.ts, src/store/filePaths.unit.ts, src/store/types/filePaths.ts
To make sure the Vue Client is up to date with changes from legacy, we should also remove/correct outdated links for files regarding privacy and terms of use similar as in https://ticketsystem.dbildungscloud.de/browse/BC-6258
BC-6482
- remove unused document links in Vue code
=> BC-6482 - Clean up code for outdated privacy and terms of use documents

src/components/organisms/administration/ImportUsers.vue
https://ticketsystem.dbildungscloud.de/browse/N21-1784
=> N21-1784 Fix migration wizard table

src/components/templates/DefaultWireframe.vue, src/components/ui-board/BoardMenuAction.vue, src/pages/context-external-tool/ContextExternalToolConfigurator.page.vue
update data test id issue in DefaultWireframe.vue file
https://ticketsystem.dbildungscloud.de/browse/BC-6643
=> BC-6643 update data test id issue

src/components/molecules/CommonCartridgeExportModal.unit.ts, src/components/molecules/CommonCartridgeExportModal.vue, src/pages/rooms/room-details.unit.ts, src/serverApi/v3/api.ts, src/store/common-cartridge-export.ts, src/store/common-cartridge-export.unit.ts, src/store/room.ts, src/store/room.unit.ts
User can control exported assignments.
- https://ticketsystem.dbildungscloud.de/browse/EW-724
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4861
=> EW-724: Control over assignments.

src/components/data-room/courseApi.composable.ts, src/components/data-room/courseApi.composable.unit.ts, src/components/data-room/index.ts, src/components/feature-course-sync/EndCourseSyncDialog.unit.ts, src/components/feature-course-sync/EndCourseSyncDialog.vue, src/components/feature-course-sync/index.ts, src/components/organisms/vCustomDialog.vue, src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/pages/administration/ClassOverview.page.unit.ts, src/pages/administration/ClassOverview.page.vue, src/pages/rooms/RoomDetails.page.vue, src/pages/rooms/room-details.unit.ts, src/serverApi/v3/api.ts, src/store/group.unit.ts, src/store/group/group.mapper.ts, src/store/types/class-info.ts, tests/test-utils/factory/classInfoFactory.ts, tsconfig.json, vue.config.js
- https://ticketsystem.dbildungscloud.de/browse/N21-1788
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4863
=> N21-1788 Stop course sync

src/pages/rooms/RoomDetails.page.vue
https://ticketsystem.dbildungscloud.de/browse/BC-6950
=> BC-6950 Wrong icon in the FAB menu for creating a new column board

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts
https://ticketsystem.dbildungscloud.de/browse/BC-6897
=> BC-6897 Adapt wording of empty state in course in Learning content

src/pages/administration/StudentOverview.page.vue, src/plugins/datetime.js, src/store/bulkConsent.js
=> BC-7000 - fix date function

src/serverApi/v3/api.ts, src/store/external-tool/mapper/common-tool.mapper.ts, src/store/external-tool/tool-parameter.enum.ts
Generates api for extended external tool
- https://ticketsystem.dbildungscloud.de/browse/N21-1836
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4876
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/253
=> N21-1836 generates api

src/serverApi/v3/api.ts
This PR will change the output of user response. The user response will be extended to show the migrated and outdated users.
https://ticketsystem.dbildungscloud.de/browse/N21-1835
=> N21 1835 show migrated user bug fix

src/components/organisms/administration/ImportUsers.vue
see the user's class assignment within migration wizard user-list
https://ticketsystem.dbildungscloud.de/browse/N21-1821
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4922
=> N21-1821 migration wizard load class assignment

src/components/administration/MigrationWarningCard.vue, src/components/organisms/administration/AuthSystems.vue
This pr fixes the ui of school administration.
- https://ticketsystem.dbildungscloud.de/browse/N21-1851
=> N21-1851 School Administraion UI Fixes

src/components/administration/ExternalToolSection.vue
show all school external tools on school administration page
- https://ticketsystem.dbildungscloud.de/browse/N21-1883
=> N21-1883 show all school external tools on school administration page

src/modules/data/external-tool/ExternalToolLaunchState.composable.ts, src/modules/data/external-tool/ExternalToolLaunchState.composable.unit.ts, src/modules/feature/media-shelf/MediaBoardExternalToolElement.unit.ts, src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue, src/modules/feature/media-shelf/MediaBoardLine.unit.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-1832
=> N21-1832 Media shelf tool launch

src/serverApi/v3/api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-1783
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/254
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4946
=> N21-1783 Remove unused lti message type

src/modules/feature/media-shelf/MediaBoardAvailableElement.unit.ts, src/modules/feature/media-shelf/MediaBoardAvailableElement.vue, src/modules/feature/media-shelf/MediaBoardAvailableLine.vue, src/modules/feature/media-shelf/MediaBoardElementDisplay.vue, src/modules/feature/media-shelf/MediaBoardExternalToolElement.unit.ts, src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue, src/modules/feature/media-shelf/MediaBoardLine.vue, src/modules/feature/media-shelf/MediaBoardLineGhost.vue, tests/test-utils/factory/externalToolDisplayDataFactory.ts, tests/test-utils/factory/media-board/mediaAvailableLineElementResponseFactory.ts
This pr changes the media shelf ui a little bit, after ux review
https://ticketsystem.dbildungscloud.de/browse/N21-1837
=> N21-1837 ui improvements

src/modules/feature/media-shelf/MediaBoardAvailableLine.unit.ts, src/modules/feature/media-shelf/MediaBoardAvailableLine.vue, src/modules/feature/media-shelf/MediaBoardExternalToolElement.unit.ts, src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue, src/modules/feature/media-shelf/MediaBoardLine.unit.ts, src/modules/feature/media-shelf/MediaBoardLine.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-1934
=> N21-1934 Fix launching on the media shelf during drag and drop

src/modules/data/external-tool/contextExternalToolState.composable.ts, src/modules/data/external-tool/contextExternalToolState.composable.unit.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-1943
=> N21-1943 Fix creation of context external tools with error

src/pages/rooms/tools/RoomExternalToolsErrorDialog.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-1953
=> N21-1953 Fix tool name in error dialog for course tools

src/components/copy-result-modal/CopyResultModal.vue, src/serverApi/v3/api.ts, src/store/copy.ts, src/store/copy.unit.ts
Add and improve logic about existance of whiteboard based on updated response from server side recursive logic.
=> BC-7162 Add information about whiteboard in copy by share token modal 

package-lock.json, package.json, src/modules/feature/board-text-element/RichTextContentElementDisplay.vue, src/modules/feature/editor/CKEditor.vue
https://ticketsystem.dbildungscloud.de/browse/BC-6970
=> BC-6970- Bump katex from 0.12.0 to 0.16.10 in nuxt-client

src/modules/data/board/BoardPageInformation.composable.ts, src/modules/data/board/BoardPageInformation.composable.unit.ts, src/modules/feature/board/board/Board.unit.ts, src/modules/feature/board/board/Board.vue, src/router/routes.ts, src/router/vue-client-route.js
- https://ticketsystem.dbildungscloud.de/browse/BC-7250
=> BC-7250 - fix redirect for /rooms path

src/modules/feature/course-sync/GroupSelectionDialog.unit.ts, src/modules/feature/course-sync/GroupSelectionDialog.vue
Adds a debounce to group search in course sync dialog
- https://ticketsystem.dbildungscloud.de/browse/N21-1966
=> N21-1996 debounce group search

src/modules/data/board/boardActions/boardActionPayload.ts, src/modules/data/board/boardActions/boardSocketApi.composable.ts, src/modules/data/board/boardActions/boardSocketApi.composable.unit.ts, src/modules/data/board/cardActions/cardActionPayload.ts, src/modules/data/board/cardActions/cardSocketApi.composable.ts, src/modules/data/board/cardActions/cardSocketApi.composable.unit.ts
As a teacher, I want to be informed when an error occurs while I am on the board. 
Jira: BC-7298
Server: https://github.com/hpi-schul-cloud/schulcloud-server/pull/5021
=> BC-7298 - Implementation Socket Error Handling (1/6): Basic error handling

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts
https://ticketsystem.dbildungscloud.de/browse/BC-7361
=> BC-7361- Adjust wording of texteditor to Etherpad

src/modules/feature/board-external-tool-element/ExternalToolElement.unit.ts, src/modules/feature/board-external-tool-element/ExternalToolElement.vue
adds default launch error in column board
https://ticketsystem.dbildungscloud.de/browse/N21-1997
=> N21-1997 default launch error in column board

src/components/rooms/RoomExternalToolCard.unit.ts, src/components/rooms/RoomExternalToolCard.vue, src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts, src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts, src/modules/feature/board-external-tool-element/ExternalToolElement.unit.ts, src/modules/feature/board-external-tool-element/ExternalToolElement.vue, src/modules/feature/board-external-tool-element/ExternalToolElementAlert.unit.ts, src/modules/feature/board-external-tool-element/ExternalToolElementAlert.vue, src/pages/rooms/tools/RoomExternalToolsErrorDialog.unit.ts, src/pages/rooms/tools/RoomExternalToolsErrorDialog.vue
adds not licensed chip and error messages in tools tab and column board in courses
- https://ticketsystem.dbildungscloud.de/browse/N21-1900
=> N21-1900 not licensed status in courses and board

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts
The title “Colums Boards” in the control options for course export is renamed to “Boards”.
https://ticketsystem.dbildungscloud.de/browse/EW-879
=> EW-879 Renaming title in control options for course export

src/modules/feature/board-external-tool-element/ExternalToolElement.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-1855
=> N21-1855 Fix small UI bugs from Vue3 migration

src/modules/feature/board-drawing-element/DrawingContentElement.vue, src/modules/feature/board/shared/AddElementDialog.composable.ts, src/modules/feature/board/shared/AddElementDialog.composable.unit.ts
https://ticketsystem.dbildungscloud.de/browse/BC-7364
=> BC-7364- Display hint for Whiteboard on the right upper corner

src/serverApi/v3/api.ts
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5030
BC-6871
=> BC-6871 - update api

src/layouts/newLoggedIn.unit.ts, src/modules/ui/layout/sidebar/Sidebar.unit.ts, src/modules/ui/layout/sidebar/SidebarCategoryItem.unit.ts, src/modules/ui/layout/sidebar/SidebarItem.unit.ts, src/modules/ui/layout/sidebar/SidebarItem.vue
Highlighting the course sidebar item on all course pages.
BC-7511
=> BC-7511 - highlight course pages

src/components/administration/ExternalToolSection.vue, src/components/administration/external-tool-section-utils.composable.ts, src/components/administration/external-tool-section-utils.composable.unit.ts, src/pages/administration/SchoolSettings.page.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2018
=> N21-2018 Add pagination to the school external tool list

src/modules/feature/media-shelf/MediaBoardLineMenu.unit.ts, src/modules/feature/media-shelf/MediaBoardLineMenu.vue
Fixes media shelfs icons for collapsed and expanded lines
- https://ticketsystem.dbildungscloud.de/browse/N21-2046
=> N21-2046 Fixes media shelf line icons

src/components/templates/DefaultWireframe.vue, src/modules/feature/board/board/Board.vue, src/pages/rooms/RoomDetails.page.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2067
=> N21-2067 Fix max-width of Courses

src/modules/feature/board/board/BoardColumnGhostHeader.vue
https://ticketsystem.dbildungscloud.de/browse/BC-7613
=> BC-7613 Fix padding in title for create new collum

src/components/administration/ExternalToolSection.unit.ts, src/components/administration/external-tool-section-utils.composable.ts, src/components/administration/external-tool-section-utils.composable.unit.ts, src/pages/administration/school-external-tool/SchoolExternalToolConfigurator.page.vue, src/serverApi/v3/api.ts, src/store/external-tool/mapper/school-external-tool.mapper.ts, src/store/external-tool/school-external-tool-configuration-status.ts, tests/test-utils/factory/schoolExternalToolConfigurationFactory.ts, tests/test-utils/factory/schoolExternalToolConfigurationStatusResponseFactory.ts, tests/test-utils/factory/schoolExternalToolResponseFactory.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-1996
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5084
=> N21-1996 Remove dynamic values from school external tool persistence

src/components/topbar/HelpDropdown.vue, src/modules/ui/layout/sidebar/SidebarItems.composable.ts
Hilfebereich als Sidebar-Item aktiv wird wenn man in die Release notes (unter "System") geht
BC-7575
- adjusting links to release notes under new parent sidebar item
=>  BC-7575 - Fix route help for "Was ist neu?"

src/serverApi/v3/api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-1547
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5101
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3477
=> N21-1547 Refactor systems module

Dockerfile
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/908
https://ticketsystem.dbildungscloud.de/browse/BC-7678
=> BC-7678 update nginx images to 1.27

src/serverApi/v3/api.ts, src/store/group.ts, src/store/group.unit.ts
Generates api
- https://ticketsystem.dbildungscloud.de/browse/N21-1511
=> N21-1511 generate api

src/serverApi/v3/api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2096
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5139
=> N21-2096 Add an endpoint to force a UserLoginMigration

src/modules/ui/room-details/SelectBoardLayoutDialog.vue
=> BC-7473 - board type dialog ADD

package-lock.json, package.json, tsconfig.json
To assure the correct project configuration after the library updates we have to make some additional changes to tsconfig.json
BC-7816
=> BC-7816 - Fix typescript config after library updates

src/plugins/vuetify.ts
We need to make sure that the Vuetify styles are not imported twice when building the frontend. Therefore we need to remove one style import from the file src/plugins/vuetify.ts
https://vuetifyjs.com/en/features/sass-variables/#component-specific-variables
BC-7844
=> BC-7844 - Remove duplicate vuetify style import

src/components/molecules/vImportUsersMatchSearch.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2117
=> N21-2117 Fix user search in dialog of migration assistant

.github/workflows/push.yml, ansible/roles/nuxt-client-core/tasks/main.yml
- hpi-schul-cloud/superhero-dashboard#262
- hpi-schul-cloud/dof_app_deploy#936
- hpi-schul-cloud/schulcloud-client#3509
- hpi-schul-cloud/schulcloud-server#5189
- hpi-schul-cloud/tldraw-client#80
- hpi-schul-cloud/version-aggregator#21
- hpi-schul-cloud/h5p-staticfiles-server#11
- hpi-schul-cloud/schulcloud-calendar#163
- hpi-schul-cloud/antivirus_check_service#58
- hpi-schul-cloud/shd-client#7
- https://ticketsystem.dbildungscloud.de/browse/BC-7854
=> BC-7854 - split Ansible Jobs by Tags

src/App.vue, src/layouts/index.ts
The board initialization is not triggered when using `<Suspense>` and `defineAsyncComponent` to load the application layouts.
BC-7918
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/946
=> BC-7918 - Board initialization not triggered when using Vue Suspense

src/pages/rooms/CourseRoomDetails.page.vue
After copying a course from the course room details page the page is not refreshed. However the URL in the browser has been updated.
BC-7923
=> BC-7923 - Course room details are not reloaded after course copy

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/modules/feature/board-deleted-element/DeletedElement.vue, src/modules/ui/board/BoardMenuActionDelete.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2160
=> N21-2160 Fix deletion of deleted element

jest.config.js
In order to get back to the default (recommended) coverage provider we want to unset coverageProvider: "v8" in our frontend jest configuration.
BC-7953
=> BC-7953 - Set default test coverage provider in frontend

src/modules/feature/board/board/Board.unit.ts, src/modules/feature/board/board/Board.vue
Release blocker
BC-7963
- reload board page after redirecting (watching route id)
=> BC-7963 - Copying Board Page Reload Issues

src/components/icons/custom/MdiCustomShelfOutline.vue, src/components/icons/custom/index.ts, src/modules/page/media-shelf/MediaShelf.page.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2088
=> N21-2088 Change media shelf line view icon

config/docker/nginx.conf.template
https://ticketsystem.dbildungscloud.de/browse/BC-3289
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/958
=> BC-3289 API_URL -> PUBLIC_BACKEND_URL

src/modules/feature/board/board/Board.unit.ts, src/modules/feature/board/board/Board.vue, src/modules/ui/room-details/RoomBoardCard.unit.ts, src/modules/ui/room-details/RoomBoardCard.vue, src/pages/course-rooms/CourseRoomDetails.page.vue, src/router/routes.ts, src/router/vue-client-route.js, src/store/copy.ts, src/store/copy.unit.ts
we want to have an actual route for the (column-) board
BC-7839
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/959
- editing `/rooms/:boardId/board => /boards/:boardId`
=> BC-7839 - Change routing for board

src/modules/ui/room-details/RoomLessonCard.vue
BC-2228
added data-testid to button publish lesson in course page
=> BC-2228 add data-testid for lesson publish link

src/serverApi/v3/api.ts
update api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2120
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5215
=> N21-2120 force migration extension api

config/webpack/webpack.common.js
Webpack output config is currently empty on process.env === development. This leads to problems starting the Frontend on developer machines.
BC-8033
=> BC-8033 - Fix Frontend development Webpack Config

src/serverApi/v3/api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2180
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5233
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3524
=> N21-2180 Fix date for synchronized courses

src/pages/administration/RoomsOverview.page.vue
add syncedWith column in course administration table
- https://ticketsystem.dbildungscloud.de/browse/N21-2184
- https://github.com/hpi-schul-cloud/e2e-system-tests/pull/239
=> N21-2184 add synced column

src/serverApi/v3/api.ts
https://ticketsystem.dbildungscloud.de/browse/BC-8018
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5248
https://github.com/hpi-schul-cloud/nuxt-client/pull/3408
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/265
=> BC-8018 Update open api client with shd route

src/pages/course-rooms/CourseRoomDetails.page.unit.ts, src/pages/course-rooms/CourseRoomDetails.page.vue
- https://ticketsystem.dbildungscloud.de/browse/BC-8204
=> BC-8204 - Fix Copied Course Redirecting

src/components/share/ShareModal.vue
Fix missing header and buttons in the share dialog.
BC-8332
=> BC-8332 - Share dialog is broken

src/pages/administration/LDAPActivate.page.vue, src/pages/administration/ldap-activate.unit.js
- hide ldap sync infos and btn for nbc
- https://ticketsystem.dbildungscloud.de/browse/N21-2195
=> N21-2195-remove-ldap-migration-assistant-btn

src/components/share/SelectDestinationModal.vue, src/modules/page/room/RoomDetails.page.unit.ts, src/modules/page/room/RoomDetails.page.vue, src/pages/course-rooms/CourseRoomDetails.page.unit.ts, src/pages/course-rooms/CourseRoomDetails.page.vue, src/router/routes.ts, src/store/course-room-details.ts
=> BC-8514 - fix room permission check

src/modules/data/board/BoardPermissions.composable.ts, src/modules/feature/board/board/Board.unit.ts, src/modules/feature/board/board/Board.vue, src/types/board/Permissions.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2294
=> N21-2294 Fix preferred tool call for students

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/modules/feature/media-shelf/MediaBoard.vue, src/modules/feature/media-shelf/MediaBoardExternalToolDeletedElement.unit.ts, src/modules/feature/media-shelf/MediaBoardExternalToolElementMenu.unit.ts, src/modules/feature/media-shelf/MediaBoardExternalToolElementMenu.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2239
=> N21-2239 Change media board delete handle

package-lock.json, package.json
=> BC-8597 - Dependency Update: Vuetify v3.7.5 to v3.7.6

src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/modules/feature/course-sync/GroupSelectionDialog.unit.ts, src/modules/feature/course-sync/GroupSelectionDialog.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2265
=> N21-2265 Small UI changes

src/pages/administration/ClassOverview.page.unit.ts, src/pages/administration/ClassOverview.page.vue, src/serverApi/v3/api.ts, src/store/group.ts, src/store/group.unit.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2270
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5414
=> N21-2270 Change group visibility for teachers that can see students

src/components/organisms/administration/AuthSystems.vue, src/components/share/ShareModalResult.vue, src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/modules/feature/board/card/CardHost.vue, src/modules/ui/kebab-menu/KebabMenuActionShareLink.unit.ts, src/modules/ui/kebab-menu/KebabMenuActionShareLink.vue, src/modules/ui/layout/topbar/PageShare.vue
- https://ticketsystem.dbildungscloud.de/browse/N21-2377
=> N21-2377 Fix board card share link action text

Dockerfile
https://ticketsystem.dbildungscloud.de/browse/BC-8965
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5509
https://github.com/hpi-schul-cloud/nuxt-client/pull/3551
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/280
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/172
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/71
https://github.com/hpi-schul-cloud/tldraw-client/pull/124
https://github.com/hpi-schul-cloud/tldraw-server/pull/53
=> BC-8965 fixup container build warnings

package-lock.json, package.json
update vuetify from 3.7.6 to 3.7.12
This will fix an issue where it was not possible to navigate through VMenus with a screenreader.
BC-8981
=> BC-8981 - update vuetify from 3.7.6 to 3.7.12

src/modules/feature/room/RoomMembers/ActionMenu.unit.ts, src/modules/feature/room/RoomMembers/ActionMenu.vue, src/modules/feature/room/RoomMembers/MembersTable.vue
Although the feature to change the role(s) of room members is not activated yet, it is possible to do so in the ActionMenu for batch-actions.
BC-9000
=> BC-9000 - fix feature toggle handling

ansible/roles/nuxt-client-core/templates/configmap.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-8998
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1114
=> BC-8998 removing nuxt-client from main config.yml

src/modules/feature/board-file-element/FileContentElement.vue
- https://ticketsystem.dbildungscloud.de/browse/BC-9088
=> BC-9088 - Remove FileContentElement not possible

package-lock.json, package.json, src/components/templates/TasksDashboardMain.unit.ts, src/components/templates/TasksDashboardStudent.unit.ts, src/modules/feature/board-link-element/components/LinkContentElement.unit.ts
Bump typescript from 5.4.3 to 5.7.3
Bump typescript-eslint from 8.11.0 to 8.25.0, because our version just supports typescript version < 5.7.0
BC-8893
=> BC-8893 - Update typescript and typescript-eslint 

src/components/organisms/administration/SchoolPolicyFormDialog.vue, src/components/organisms/administration/SchoolTermsFormDialog.vue
JIRA :
- https://ticketsystem.dbildungscloud.de/browse/BC-8685
Deployments :
- https://bc-8685.dbc.dbildungscloud.dev/
- https://bc-8685.brb.dbildungscloud.dev/
- https://bc-8685.nbc.dbildungscloud.dev/
- https://bc-8685.thr.dbildungscloud.dev/
=> BC-8685 - Check & Activate privacy policy/terms of use upload on new admin page (Staging NBC)

package-lock.json, package.json
Update `pinia` from `2.1.7` to `3.0.0`
BC-9140
=> BC-9140 - Update pinia to 3.0.0

package-lock.json, package.json
Update vue-router from 4.4.5 to 4.5.0
BC-9146
=> BC-9146 - Update vue-router from 4.4.5 to 4.5.0

package-lock.json, package.json
=> BC-9244 - update ckeditor

src/components/atoms/vRoomAvatar.vue
=> BC-9264 - fix RoomAvatar being circular in GroupRoomAvatar

src/modules/feature/board-link-element/components/LinkContentElement.unit.ts, src/modules/feature/board-link-element/components/LinkContentElement.vue, src/modules/feature/board/board/Board.unit.ts, src/modules/feature/board/board/Board.vue, src/modules/util/board/elementFocus.composable.ts, src/modules/util/board/elementFocus.composable.unit.ts, src/modules/util/board/index.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2445
=> N21-2445 Fix board scrolling on Firefox

src/modules/feature/board-file-element/content/display/audio-display/AudioDisplay.vue, src/modules/feature/board-file-element/content/display/image-display/ImageDisplay.vue, src/modules/feature/board-file-element/content/display/video-display/VideoDisplay.vue, src/modules/ui/light-box/LightBox.vue, src/modules/ui/preview-image/PreviewImage.vue
BC-9173
- Added data-testids related to the file element.
=> BC-9173 Add data-testid in File Element

src/serverApi/v3/api.ts, src/store/external-tool/mapper/common-tool.mapper.ts, tests/test-utils/factory/customParameterResponseFactory.ts, tests/test-utils/factory/toolLaunchRequestResponseFactory.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2478
=> N21-2478 Generate server API

src/modules/feature/room/RoomMembers/AddMembers.vue
Show focus indicator for close button on member chips.
BC-8603
- set overflow from v-chip to `overflow: unset` because `overflow: hidden` will cause that focus indicator is not shown on Safari (vuetify bug) -> the chip content still has `overflow:hidden`
=> BC-8603 - Fix focus indicator for member chips on Safari

src/components/templates/DefaultWireframe.unit.ts, src/components/templates/DefaultWireframe.vue, src/modules/feature/room/RoomMembers/ActionMenu.unit.ts, src/modules/feature/room/RoomMembers/ActionMenu.vue, src/modules/feature/room/RoomMembers/MembersTable.unit.ts, src/modules/feature/room/RoomMembers/MembersTable.vue, src/modules/page/room/RoomMembers.page.vue
For reusing the actionMenu (used for batch actions) on other room-membership related functionalities, it needs to be refactored.
BC-9107
=> BC-9107 - refactor the action menu of the room-members-page

package-lock.json, package.json
- https://ticketsystem.dbildungscloud.de/browse/N21-2503
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5651
- https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/19
=> N21-2503 Update H5P libraries

src/serverApi/v3/api.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2505
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5660
=> add single medium metadata fetch & update error handling

src/modules/feature/board-h5p-element/H5pElement.unit.ts, src/modules/feature/board-h5p-element/H5pElement.vue, src/pages/h5p/H5PEditor.page.vue, src/pages/h5p/H5PPlayer.page.unit.ts, src/pages/h5p/H5PPlayer.page.vue, src/router/routes.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2497
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3635
=> N21-2497 Play H5P content in board

src/modules/feature/room/RoomGrid.unit.ts, src/modules/feature/room/RoomGrid.vue
EmptyState for rooms now uses the correct language key
BC-9792
=> BC-9792 - use correct language key for empty rooms

.github/workflows/dependency-review.yml
https://ticketsystem.dbildungscloud.de/browse/BC-9800
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5712
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3644
https://github.com/hpi-schul-cloud/nuxt-client/pull/3715
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/308
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/202
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/90
https://github.com/hpi-schul-cloud/tldraw-client/pull/167
https://github.com/hpi-schul-cloud/dependency-review-config/pull/2
=> BC-9800 use centralized dependency-review config

config/webpack/webpack.common.js, config/webpack/webpack.prod.js
Now frontend build does not fail for dev environment when eslint errors occur
BC-9869
=> BC-9869 - prevent frontend build from failing for dev when eslint errors occur

src/components/external-tools/configuration/ExternalToolConfigurator.unit.ts, src/components/external-tools/configuration/ExternalToolMediumDetails.unit.ts, src/components/external-tools/configuration/ExternalToolMediumDetails.vue, src/locales/de.ts, src/locales/en.ts, src/locales/es.ts, src/locales/uk.ts, src/pages/administration/school-external-tool/SchoolExternalToolConfigurator.page.unit.ts, src/pages/administration/school-external-tool/SchoolExternalToolConfigurator.page.vue
- show admin ctl template details in school external tool configurator
- https://ticketsystem.dbildungscloud.de/browse/N21-2571
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5760
- school external tool configurator
=> N21-2571 show admin ctl template details

src/components/rooms/RoomBaseCard.vue, src/components/rooms/RoomExternalToolCard.unit.ts, src/components/rooms/RoomExternalToolCard.vue, src/modules/data/external-tool/externalToolReferenceApi.composable.unit.ts, src/modules/data/external-tool/types/external-tool-display-data.ts, src/modules/feature/board-external-tool-element/ExternalToolElement.unit.ts, src/modules/feature/board-external-tool-element/ExternalToolElement.vue, src/modules/feature/media-shelf/MediaBoardAvailableElement.unit.ts, src/modules/feature/media-shelf/MediaBoardAvailableElement.vue, src/modules/feature/media-shelf/MediaBoardElementDisplay.unit.ts, src/modules/feature/media-shelf/MediaBoardElementDisplay.vue, src/modules/feature/media-shelf/MediaBoardExternalToolElement.unit.ts, src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue, src/modules/feature/media-shelf/data/types.ts, src/modules/ui/board/content-element/ContentElementBar.vue, src/modules/ui/line-clamp/LineClamp.vue, src/pages/course-rooms/tools/RoomExternalToolsErrorDialog.unit.ts, src/serverApi/v3/api.ts, src/store/external-tool/mapper/common-tool.mapper.ts, src/store/external-tool/mapper/external-tool.mapper.ts, src/store/external-tool/tool-parameter-location.enum.ts, tests/test-utils/factory/externalToolDisplayDataFactory.ts, tests/test-utils/factory/media-board/mediaAvailableLineElementResponseFactory.ts, tests/test-utils/factory/toolReferenceResponseFactory.ts
- https://ticketsystem.dbildungscloud.de/browse/N21-2417
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5757
- https://github.com/hpi-schul-cloud/e2e-system-tests/pull/350
=> N21-2417 Add domain info to external tool links

.github/pull_request_template.md
Implementing a checkbox for added Cypress tests for new features in FE PR template.
BC-10029
=> BC-10029 - Add checkbox for Cypress tests into FE PR

.github/workflows/push.yml, .github/workflows/test.yml, .github/workflows/trivy.yml
https://ticketsystem.dbildungscloud.de/browse/BC-10096
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5783
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3664
https://github.com/hpi-schul-cloud/nuxt-client/pull/3778
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/315
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/96
https://github.com/hpi-schul-cloud/version-aggregator/pull/37
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/21
https://github.com/hpi-schul-cloud/tldraw-client/pull/182
https://github.com/hpi-schul-cloud/tldraw-server/pull/68
https://github.com/hpi-schul-cloud/file-storage/pull/32
> Notice: Please keep this Pull-Request as a Draft (or add …
=> BC-10096 update gh-actions

src/serverApi/v3/api.ts
Generated the client after removal of old CC Import in the server.
- https://ticketsystem.dbildungscloud.de/browse/EW-1076
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5799
=> EW-1076: Update generated client.

src/modules/data/room/roomMembers/RoomMembers.store.ts, src/modules/data/room/roomMembers/RoomMembers.store.unit.ts
=> BC-10243 - Fix Add Member Error

sonar-project.properties
- hpi-schul-cloud/schulcloud-server#5844
- hpi-schul-cloud/file-storage#69
- hpi-schul-cloud/tldraw-server#75
- https://ticketsystem.dbildungscloud.de/browse/BC-10418
=> BC-10418 - deaktivate githubcation scan from sonar

src/modules/data/board/boardActions/boardSocketApi.composable.unit.ts, src/modules/data/board/cardActions/cardSocketApi.composable.unit.ts, src/modules/feature/board-link-element/components/LinkContentElement.unit.ts, src/modules/feature/board/board/Board.unit.ts, src/modules/feature/board/board/Board.vue, src/modules/feature/editor/EditorConfig.composable.ts, src/modules/util/board/elementFocus.composable.ts, src/modules/util/board/elementFocus.composable.unit.ts, tests/test-utils/factory/boardResponseFactory.ts
=> BC-10556  - Fixing the card element highlighting issue on dbc

src/modules/feature/board-external-tool-element/ExternalToolElement.vue, src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.vue
- Fix alert positioning at video conference and tool element
https://ticketsystem.dbildungscloud.de/browse/BC-10648
=> BC-10648 - Fix alert at video conference element

src/modules/page/room/RoomDetails.page.unit.ts, src/modules/page/room/RoomEdit.page.unit.ts, src/modules/page/room/RoomMembers.page.unit.ts, src/modules/page/room/Rooms.page.unit.ts
=> BC10591 - Fix typings after merge on ticket was completed

src/components/organisms/administration/GeneralSettings.vue, src/modules/util/board/shareBoardLink.composable.ts
It looks like we did not pay enough attention when merging and two translations went missing.
- https://ticketsystem.dbildungscloud.de/browse/BC-10769
=> BC-10769: Add missing translations
